### PR TITLE
Apetree100122 patch 2

### PR DESCRIPTION
**Pull request by Apetree100122**
#### What kind of change does this PR introduce?

(Is it a bug fix, feature, docs update, something else?)

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the new behavior (if this is a feature change)?**

- [x] Tests for the changes have been added (for bug fixes/features)

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note

```

### CODE REVIEW

**Review by Apetree100122 — COMMENTED** [review]
i think these   will be more efficient

**Comment by Apetree100122** [comment]
thanks for consideration

**Review by spencerschrock — CHANGES_REQUESTED** [review]
Can you describe what you're trying to patch? This PR appears to be a lot of formatting changes which violate `go fmt` and also include invalid changes to `go.mod`, and commenting out some constants.

**Comment by justaugustus** [comment]
Feel free to reopen this PR for discussion if it is in fact legitimate.

**Pull request closed without merging**
