### PR TITLE
🐛 Discard GitHub token in dangerous workflow check

### PR DESCRIPTION
**Pull request by laurentsimon**
Don't alert if the default GH token is used on pull requests. See https://github.com/ossf/scorecard/issues/1770
No breaking changes
```release-notes
Don't alert if the default GH token is used on pull requests
```
closes https://github.com/ossf/scorecard/issues/1770

### CODE REVIEW

**Review by naveensrinivasan — APPROVED** [review]
Thanks, I was also thinking of the same. Cool!

**Comment by laurentsimon** [comment]
All my PRs are failing with:
```
protoc --go_out=../../../ cron/data/request.proto
/bin/bash: protoc: command not found
make: *** [Makefile:10[8](https://github.com/ossf/scorecard/runs/5652653919?check_suite_focus=true#step:7:8): cron/data/request.pb.go] Error 127
```

**Comment by laurentsimon** [comment]
@naveensrinivasan @azeemsgoogle any ideas why PRs are suddenly all failing with protobuf errors?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan @azeemsgoogle any ideas why PRs are suddenly all failing with protobuf errors?

I am tired of fixing it TBH. We need to find a way to retry it or do something about this.

**Pull request merged**
