### PR TITLE
:seedling: Fixes OSV GO-2021-0053

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
 Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
   https://deps.dev/advisory/OSV/GO-2021-0053?from=%2Fgo%2Fgithub.com%252Fossf%252Fscorecard

* **What is the new behavior (if this is a feature change)?**
  * Fixes the OSV issue GO-2021-0053

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
No

### CODE REVIEW

**Review by azeemshaikh38 — APPROVED** [review]

**Comment by naveensrinivasan** [comment]
The unit test is broken with this upgrade which needs to be addressed.

**Comment by naveensrinivasan** [comment]
@laurentsimon  Would you be able to address these issues on the unit tests? I know you are familiar with those. Thanks

**Comment by laurentsimon** [comment]
> @laurentsimon Would you be able to address these issues on the unit tests? I know you are familiar with those. Thanks

https://github.com/ossf/scorecard/issues/986. I'll take it if nobody wants to.

**Comment by naveensrinivasan** [comment]
> > @laurentsimon Would you be able to address these issues on the unit tests? I know you are familiar with those. Thanks
> 
> #986. I'll take it if nobody wants to.

Thank you!

**Comment by naveensrinivasan** [comment]
Fixed it by updating the mod file.

**Pull request closed without merging**
