### PR TITLE
📖  Update Install command for version 3

### PR DESCRIPTION
**Pull request by olivekl**
Change v2@latest to v@latest in README.md

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update

* **What is the current behavior?** (You can also link to an open issue here)
Old version in install command

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by azeemshaikh38** [comment]
> Looks like it by design [golang/go#44840](https://github.com/golang/go/issues/44840). My suggestion would be is to change to `go get github.com/ossf/scorecard/v3@latest`
> 
> ```
>  go get github.com/ossf/scorecard/v3@latest
> go: downloading github.com/ossf/scorecard/v3 v3.0.1
> go: downloading github.com/ossf/scorecard v1.2.0
> ```

Hmm, it still fails for me:

```
go get github.com/ossf/scorecard/v3@latest
go get: installing executables with 'go get' in module mode is deprecated.
        Use 'go install pkg@version' instead.
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
```

**Comment by naveensrinivasan** [comment]
> > Looks like it by design [golang/go#44840](https://github.com/golang/go/issues/44840). My suggestion would be is to change to `go get github.com/ossf/scorecard/v3@latest`
> > ```
> >  go get github.com/ossf/scorecard/v3@latest
> > go: downloading github.com/ossf/scorecard/v3 v3.0.1
> > go: downloading github.com/ossf/scorecard v1.2.0
> > ```
> 
> Hmm, it still fails for me:
> 
> ```
> go get github.com/ossf/scorecard/v3@latest
> go get: installing executables with 'go get' in module mode is deprecated.
>         Use 'go install pkg@version' instead.
>         For more information, see https://golang.org/doc/go-get-install-deprecation
>         or run 'go help get' or 'go help install'.
> ```

It is not a failure. It is a warning. It will be installed. You can `rm scorecard` and figure out the path of `which scorecard`. After `go get` scorecard will be there.

**Comment by azeemshaikh38** [comment]
> It is not a failure. It is a warning. It will be installed. You can `rm scorecard` and figure out the path of `which scorecard`. After `go get` scorecard will be there.

Yeah that did work. I wonder if that's what we should be asking our users to do though. What's the reason for having the `replace` directives? Can we remove them altogether?

**Comment by azeemshaikh38** [comment]
> > > The replace is for not having these OSV's.
> > 
> > 
> > Makes sense. In that case, we should keep the `replace` directives.
> > From [golang/go#40276](https://github.com/golang/go/issues/40276), my understanding of the issue is this - `go install` _compiles_ the package. Hence, `replace` directives are not honored since they can cause inconsistencies between builds. In case of Scorecard, this is actually true - the binary available to be downloaded from the [release page](https://github.com/ossf/scorecard/releases/) has the correct `version` and `commit` info. But the binary from `go install` does not have this information.
> > Here's my suggestion - how about we ask users to download the `scorecard` binary from the release page (similar to what `protoc` does). That way we can continue using `replace` and also guarantee consistency on our binaries. Wdyt @naveensrinivasan ?
> 
> I concur we should ask users to download the binary from GitHub releases rather than `go install`.
> 
> Thanks!

Thanks. @olivekl can you update the documentation here to reflect this? Basically, we want users to visit our [latest release](https://github.com/ossf/scorecard/releases/latest) page. From there, they will need to download and extract the right binary (Linux, Mac or Windows) and add this to their `GOPATH/bin`.

**Pull request merged**
