### PR TITLE
🌱  add github.com/intel public repos

### PR DESCRIPTION
**Pull request by rdower**
#### What kind of change does this PR introduce? 
Updates to csv to add repos to scorecard
(Is it a bug fix, feature, docs update, something else?)

- [ ] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the new behavior (if this is a feature change)?**

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

**Review by naveensrinivasan — COMMENTED** [review]
Thanks, please DCO your commit.

**Comment by spencerschrock** [comment]
Also note there is some validation on the `projects.csv` file which is currently failing. 
`make validate-projects` will run the validator tool.

**Comment by rdower** [comment]
I made an error in this PR trying to update. Will close and resubmit

**Comment by spencerschrock** [comment]
Just for your awareness, the validator script quits at the first mismatch. There are likely more duplicate projects.
```
$ grep github.com/intel/ projects.csv | wc -l
65
```

**Comment by spencerschrock** [comment]
`make add-projects` should be more useful. Forgot about it the first time

**Comment by rdower** [comment]
Thank you, Spencer!!

**Pull request closed without merging**
