### PR TITLE
🌱 go.mod: Update github.com/google/go-containerregistry to v0.8.0

### PR DESCRIPTION
**Pull request by justaugustus**
* **Please check if the PR fulfills these requirements**
- [x] (N/A) Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

  🌱 go.mod: Update github.com/google/go-containerregistry to v0.8.0

  ref: https://github.com/ossf/scorecard/issues/1382, https://github.com/ossf/scorecard/pull/1281

  Signed-off-by: Stephen Augustus <foo@auggie.dev>

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by justaugustus** [comment]
(Planning to bump ggcr to v0.8.0, but I want to check in on the failures in https://github.com/ossf/scorecard/issues/1382 first.)

**Comment by justaugustus** [comment]
CI passed on ggcr@v0.7.0, so I've bumped to v0.8.0.

**Review by azeemshaikh38 — APPROVED** [review]
Woo hoo, this has been pending for so long. Thanks @justaugustus!

**Comment by justaugustus** [comment]
> Woo hoo, this has been pending for so long. Thanks @justaugustus!

No problem!!

**Pull request merged**
