### PR TITLE
🐛 Bug fixing: recurring results of the scorecard fuzzing check for go built-in fuzzers

### LINKED ISSUE #2098: BUG: The Scorecard fuzzing check sometimes has recurring extra results
**Describe the bug**
The Scorecard fuzzing check reports recurring extra `GoBuiltInFuzzer` in the fuzzing results and its details.

**Reproduction steps**
This was initially brought up in issue #2060. Now it also shows in https://deps.dev/go/github.com%2Fgabriel-vasile%2Fmimetype/
```
project is fuzzed with [GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer GoBuiltInFuzzer ...
```
and in the details:
```
Info: func FuzzFromXML(f *testing.F): internal/charset/charset_test.go:128
Info: func FuzzMimetype(f *testing.F): mimetype_test.go:618
Info: func FuzzFromPlain(f *testing.F): internal/charset/charset_test.go:89
Info: func FuzzFromHTML(f *testing.F): internal/charset/charset_test.go:106
Info: func FuzzFromXML(f *testing.F): internal/charset/charset_test.go:128
Info: func FuzzMimetype(f *testing.F): mimetype_test.go:618
Info: func FuzzFromPlain(f *testing.F): internal/charset/charset_test.go:89
Info: func FuzzFromHTML(f *testing.F): internal/charset/charset_test.go:106
Info: func FuzzFromXML(f *testing.F): internal/charset/charset_test.go:128
Info: func FuzzMimetype(f *testing.F): mimetype_test.go:618
Info: func FuzzFromPlain(f *testing.F): internal/charset/charset_test.go:89
Info: func FuzzFromHTML(f *testing.F): internal/charset/charset_test.go:106
Info: func FuzzFromXML(f *testing.F): internal/charset/charset_test.go:128
Info: func FuzzMimetype(f *testing.F): mimetype_test.go:618
...
```

**Expected behavior**
It should've only reported one `GoBuiltInFuzzer` and maybe multiple fuzzer funcs in the details.

**Additional context**
I tried to run the fuzzing check on the repo that triggered the bug with `go run . --repo github.com/gabriel-vasile/mimetype --checks Fuzzing --show-details`, and the result in my local seems fine:
```project is fuzzed with [GoBuiltInFuzzer]```
and 
```
Info: func FuzzFromXML(f *testing.F): internal/charset/charset_test.go:128
Info: func FuzzMimetype(f *testing.F): mimetype_test.go:618
Info: func FuzzFromPlain(f *testing.F): internal/charset/charset_test.go:89
Info: func FuzzFromHTML(f *testing.F): internal/charset/charset_test.go:106
```

I also took a look into the corresponding code snippet and failed to identify the buggy part - [the code](https://github.com/ossf/scorecard/blob/main/checks/raw/fuzzing.go#L100-L118) would iterate an array of prominent languages returned by the [GitHub language API](https://docs.github.com/en/rest/repos#list-languages) and check the fuzzers **only once per language**, and theoretically, the GitHub API shouldn't give any duplicated language entries for a repository.

However, according to the results, it is most likely that one language shows multiple times in the prominent language array (like `["Go", "Go", "Go", "Go", ...]`) and thus our program iterated `Go` several times and gave duplicated results.

I'll add a patch to drop the potential language duplicates, but still, i'm not sure if this is the root cause.

cc: @laurentsimon @oliverchang

### PR DESCRIPTION
**Pull request by aidenwang9867**
#### What kind of change does this PR introduce?
A bug fix: issue #2098 

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
Under some specific circumstances, the scorecard fuzzing check returns extra recurring fuzzer results for Go built-in fuzzers. See issues #2060 and #2098.

#### What is the new behavior (if this is a feature change)?**
I am using a hashmap to drop potential duplicated prominent languages (theoretically there won't be any), so it is expected the fuzzing results will be correctly reported without any recurring contents.

- [x] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
Fixes #2098 

#### Does this PR introduce a user-facing change?
No.

```release-note
NONE
```

### CODE REVIEW

**Comment by aidenwang9867** [comment]
@laurentsimon @oliverchang

**Review by laurentsimon — COMMENTED** [review]
Could you add some unit tests?

**Comment by aidenwang9867** [comment]
> Could you add some unit tests?

done, please see https://github.com/ossf/scorecard/pull/2101/files#diff-97593777ce7b8e3b0e3c50d4e8ea916cb608d7c8dae398b083bfb737fcd76d1f and https://github.com/ossf/scorecard/pull/2101/files#diff-04e59c883164f265602b7660801c8c9663e4d7787b7b3d649d0114cc6655a1c2

**Review by laurentsimon — APPROVED** [review]
Thanks

**Pull request merged**
