### PR TITLE
:book: Add correct contact to CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by calebbrown**
Signed-off-by: Caleb Brown <calebbrown@google.com>

#### What kind of change does this PR introduce?

Docs Update

- [X] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

`[INSERT CONTACT METHOD]` is in the code of conduct.

#### What is the new behavior (if this is a feature change)?**

Replace `[INSERT CONTACT METHOD]` with actual contact conduct@openssf.org (as verified in Slack).

- [X] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

NONE

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

**Review by azeemshaikh38 — APPROVED** [review]

**Review by olivekl — APPROVED** [review]
Sorry for the delay. Thanks for this, LGTM & approval.

**Comment by spencerschrock** [comment]
The CI will never succeed for this, we'll need to fix the workflow:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks

**Comment by spencerschrock** [comment]
There doesn't seem to be any native way of fixing the skipped checks, for reasons that this blog sums up well.
https://blog.pantsbuild.org/skipping-github-actions-jobs-without-breaking-branch-protection/

**Comment by laurentsimon** [comment]
> There doesn't seem to be any native way of fixing the skipped checks, for reasons that this blog sums up well. https://blog.pantsbuild.org/skipping-github-actions-jobs-without-breaking-branch-protection/

I've not read the link, but I think you can declare an additional job that depends on the skipped, and mark the new job `if: always()` and use that job in branch protection. We do something similar on the SLSA repos.

**Comment by spencerschrock** [comment]
> > There doesn't seem to be any native way of fixing the skipped checks, for reasons that this blog sums up well. https://blog.pantsbuild.org/skipping-github-actions-jobs-without-breaking-branch-protection/
> 
> I've not read the link, but I think you can declare an additional job that depends on the skipped, and mark the new job `if: always()` and use that job in branch protection. We do something similar on the SLSA repos.

I think this is a little different. The jobs are never scheduled due to the path filtering at the top. I don't think `always()` would run as the job isn't skipped, it's never scheduled. But I can try an experiment.

**Review by spencerschrock — APPROVED** [review]

**Pull request merged**
