### PR TITLE
:warning: Allow probes to specify their own bad outcomes

### LINKED ISSUE #3654: evaluate probe outcomes for probes identifying negative behaviors
Creating from: https://github.com/ossf/scorecard/pull/3507#discussion_r1380773897. It's common for probes to look for the existence of dangerous/risky data points. When such things are found, should the outcome be positive or negative?

>>  Should the probe be called repositoryIsArchived instead [of notArchived]?
>
> Then we have the dilemma:
>
> If we return OutcomePositive, we convey that it is positive that the project is archived.
> If we return OutcomeNegative, the return value is negative, but we consider it positive, since it is positive that the repository is not archived.

### PR DESCRIPTION
**Pull request by spencerschrock**
#### What kind of change does this PR introduce?

structured result breaking change

- [X] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
`OutcomeNegative` which was always assumed to be negative, got changed to `OutcomeFalse`, which isn't always a bad thing. Some probes detect dangerous behaviors, which would mean the remediation should be applied to OutcomeTrue.

#### What is the new behavior (if this is a feature change)?**

 The `github.com/ossf/scorecard/v4/finding/probe` package was merged into `github.com/ossf/scorecard/v4/finding`. 

Probes can declare in their YAML which outcome should cause the findings to have a remediation. This is done by specifying a `onOutcome` field under `remediation` in the yaml:
```yaml
remediation:
  # can be True or False depending on how the probe is phrased
  onOutcome: True 
```

This enables fixing the outcome/probe names for some probes.

1. Several probes were phrased in a way that the conversion from OutcomePositive/Negative to True/False made the returned outcomes wrong because they identified bad behaviors. These were fixed so OutcomeTrue is interpreted negatively.
  * `hasOSVVulnerabilities` 
  * `hasDangerousWorkflowScriptInjection`
  * `hasDangerousWorkflowUntrustedCheckout`

2. Other probes were phrased in a way to avoid confusion mentioned in #3866. These probes have been chnaged as follows:
  * `notCreatedRecently` -> `createdRecently`
  * `freeOfAnyBinaryArtifacts` -> `hasBinaryArtifacts`
  * `freeOfUnverifiedBinaryArtifacts` -> `hasUnverifiedBinaryArtifacts`
  * `notArchived` -> `archived`
 
 
- [X] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
Fixes #3654 

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

**Comment by laurentsimon** [comment]
> @laurentsimon this is still a WIP as I need to switch around more probes.
> 
> But this commit ([eec4665](https://github.com/ossf/scorecard/commit/eec4665eb841e5787109ee40906e0f9a307882f0)) shows the new field 

I was thinking we'd create a new field in the def.yml:

```yaml
- remediation
  on: true | false
```
and use that to determine when remediation is necessary

**Comment by laurentsimon** [comment]
> > @laurentsimon this is still a WIP as I need to switch around more probes.
> > But this commit ([eec4665](https://github.com/ossf/scorecard/commit/eec4665eb841e5787109ee40906e0f9a307882f0)) shows the new field
> 
> I was thinking we'd create a new field in the def.yml:
> 
> ```yaml
> - remediation
>   on: true | false
>   text: bla 
>   ...
> ```
> 
> and use that to determine when remediation needs to be populated. Having in def.yml also helps with documentation

Sorry, that's basically what you did - I missed the example .yml files and was looking for a def.yml. Yeah We're on the same page. +1 on having badOutcome private!

**Comment by spencerschrock** [comment]
> > > @laurentsimon this is still a WIP as I need to switch around more probes.
> > > But this commit ([eec4665](https://github.com/ossf/scorecard/commit/eec4665eb841e5787109ee40906e0f9a307882f0)) shows the new field
> > 
> > 
> > I was thinking we'd create a new field in the def.yml:
> > ```yaml
> > - remediation
> >   on: true | false
> >   text: bla 
> >   ...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and use that to determine when remediation needs to be populated. Having in def.yml also helps with documentation
> 
> Sorry, that's basically what you did - I missed the example .yml files and was looking for a def.yml. Yeah We're on the same page. +1 on having badOutcome private!

I like the nested `on:` field better. I'll make the change tomorrow.

**Comment by spencerschrock** [comment]
/scdiff generate Pinned-Dependencies,Contributors,Security-Policy,Vulnerabilities,Branch-Protection,SAST,CII-Best-Practices,Dangerous-Workflow,Code-Review,Token-Permissions,Signed-Releases,Fuzzing,License,CI-Tests,Binary-Artifacts,Dependency-Update-Tool,Maintained,Packaging

**Review by laurentsimon — APPROVED** [review]

**Pull request merged**
