### PR TITLE
:seedling: Fix for empty repository

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Fixes the score to `0` for an empty repository.
- Fixes https://github.com/ossf/scorecard/issues/2157

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@azeemshaikh38  👀 . I haven't handled the SARIF yet but wanted feedback prior to that.

**Comment by naveensrinivasan** [comment]
@azeemshaikh38  a friendly ping

**Review by azeemshaikh38 — COMMENTED** [review]
The simpler fix might be to return an empty `ScorecardResult{}` struct here when there are no commits found - https://github.com/ossf/scorecard/blob/6fc08e7c9ce05bbff1329e777b2eca38cb41564f/pkg/scorecard.go#L97 ?

**Comment by naveensrinivasan** [comment]
> The simpler fix might be to return an empty `ScorecardResult{}` struct here when there are no commits found -
> 
> https://github.com/ossf/scorecard/blob/6fc08e7c9ce05bbff1329e777b2eca38cb41564f/pkg/scorecard.go#L97
> 
> ?

Cool, Thanks took care of it here https://github.com/ossf/scorecard/pull/2207

**Pull request closed without merging**
