### PR TITLE
✨ Support `Security-Policy` with `--local`

### LINKED ISSUE #1752: BUG: Security-Policy throws internal error if `--local .` passed
**Describe the bug**
`$ scorecard --local .` throws `input repo should be of type repoURL` error.

**Reproduction steps**
1. `$ git clone github.com/chainguard-dev/apko`
2. `$ scorecard --local .`
3. See: `internal error: input repo should be of type repoURL: <nil>`

**Expected behavior**
We should not print out `Security-Policy` section in case we don't pass `--repo` flag?

**Additional context**
Version: `4.1.0`

### PR DESCRIPTION
**Pull request by azeemshaikh38**
#### What kind of change does this PR introduce?

(Is it a bug fix, feature, docs update, something else?)

Add localclient support for `Security-Policy` check.

- [ ] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the new behavior (if this is a feature change)?**

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

Fixes #1752

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
Support `Security-Policy` with `--local`
```

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
LGTM, does this check support local repos? It's downloading the org repo if it exists, so it would return an error when security file is missing with the `--local` option, no?

**Comment by azeemshaikh38** [comment]
> LGTM, does this check support local repos? It's downloading the org repo if it exists, so it would return an error when security file is missing with the `--local` option, no?

That was the behavior before this PR. With this PR, it only looks at the org repo if the `Repo.Org() != nil` and returns a min score otherwise.

**Comment by laurentsimon** [comment]
I think the problem was introduced in https://github.com/ossf/scorecard/pull/1822. This PR declared this check as File-based, even though the checks.yml says it's not https://github.com/ossf/scorecard/blob/main/docs/checks/internal/checks.yaml#L539

**Comment by azeemshaikh38** [comment]
> I think the problem was introduced in #1822. This PR declared this check as File-based, even though the checks.yml says it's not https://github.com/ossf/scorecard/blob/main/docs/checks/internal/checks.yaml#L539
> 
> I think we need to make this check _not_ file/commit type.

Discussed offline. `--local` will not run `Security-Policy` check. We'll only use this check for GitHub-like VCS platforms.

**Pull request merged**
