### PR TITLE
:seedling: Vendor dependencies

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)
 Fixes https://github.com/ossf/scorecard/issues/1188

* **What is the new behavior (if this is a feature change)?**
  Vendor dependencies for hermetic builds.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

Dependabot can upgrade packages even if they are vendored. Example https://github.com/tektoncd/chains/commit/76face8707fef6dde70673cad36eb38ca16c6533#diff-630ba09448af522154f38ef7685ef1f44b0f3e9430f80829a03ce24f400f3754

### CODE REVIEW

**Comment by azeemshaikh38** [comment]
Have we reached a consensus on #1188 yet to submit this PR? @laurentsimon @inferno-chromium fyi.

**Comment by naveensrinivasan** [comment]
> Have we reached a consensus on #1188 yet to submit this PR? @laurentsimon @inferno-chromium fyi.

It was simple to do. If we don't agree then I can close it.

**Comment by laurentsimon** [comment]
> > Have we reached a consensus on #1188 yet to submit this PR? @laurentsimon @inferno-chromium fyi.
> 
> It was simple to do. If we don't agree then I can close it.

I don't have a strong opinion. It helps for hermetic builds, but nobody can verify yet, so it's not urgent. It may be useful to merge this PR to explore how vendoring works and if there are problems with it we have not anticipated - to inform guidelines for OSS in general. TL:DR: I'm fine with this PR.

**Review by laurentsimon — APPROVED** [review]

**Comment by azeemshaikh38** [comment]
> > > Have we reached a consensus on #1188 yet to submit this PR? @laurentsimon @inferno-chromium fyi.
> > 
> > 
> > It was simple to do. If we don't agree then I can close it.
> 
> I don't have a strong opinion. It helps for hermetic builds, but nobody can verify yet, so it's not urgent. It may be useful to merge this PR to explore how vendoring works and if there are problems with it we have not anticipated - to inform guidelines for OSS in general. TL:DR: I'm fine with this PR.

I'm on the same page. Although I personally don't fully understand the pros/cons of vendoring dependencies. @oliverchang do you have any feedback here?

**Comment by laurentsimon** [comment]
> > > > Have we reached a consensus on #1188 yet to submit this PR? @laurentsimon @inferno-chromium fyi.
> > > 
> > > 
> > > It was simple to do. If we don't agree then I can close it.
> > 
> > 
> > I don't have a strong opinion. It helps for hermetic builds, but nobody can verify yet, so it's not urgent. It may be useful to merge this PR to explore how vendoring works and if there are problems with it we have not anticipated - to inform guidelines for OSS in general. TL:DR: I'm fine with this PR.
> 
> I'm on the same page. Although I personally don't fully understand the pros/cons of vendoring dependencies. @oliverchang do you have any feedback here?

One concern is repo size. How much is our repo going to be? Say, we run scorecard on our own repo which vendors dependencies: will the tarball contain all the dependencies? Scorecard will OOM if this is the case. 
I know github supports submodule links, is this possible in our case?

If we want to vendor dependencies for hermetic building, then it may be better to run `go mod vendor` followed by `go build` at release time, rather than having a copy of all dependencies in our repo? And if we also want to comply with SLSA's "history is kept for ever", then we can make the dependencies fetched part of the released artifact on GitHub - if its not too big, or somewhere else.

**Comment by naveensrinivasan** [comment]
> > > > > Have we reached a consensus on #1188 yet to submit this PR? @laurentsimon @inferno-chromium fyi.
> > > > 
> > > > 
> > > > It was simple to do. If we don't agree then I can close it.
> > > 
> > > 
> > > I don't have a strong opinion. It helps for hermetic builds, but nobody can verify yet, so it's not urgent. It may be useful to merge this PR to explore how vendoring works and if there are problems with it we have not anticipated - to inform guidelines for OSS in general. TL:DR: I'm fine with this PR.
> > 
> > 
> > I'm on the same page. Although I personally don't fully understand the pros/cons of vendoring dependencies. @oliverchang do you have any feedback here?
> 
> One concern is repo size. How big is our repo going to be? Say, we run scorecard on our own repo which vendors dependencies: will the tarball contain all the dependencies? Scorecard will OOM if this is the case. I know github supports submodule links, is this possible in our case?
> 
> If we want to vendor dependencies for hermetic building, then it may be better to run `go mod vendor` followed by `go build` at release time, rather than having a copy of all dependencies in our repo? And if we also want to comply with SLSA's "history is kept for ever", then we could keep a copy of fetched dependencies as part of the released artifact on GitHub - if it's not too big, or somewhere else.

This is the case with Kubernetes/Kubernetes and scorecard doesn't OOM.

**Comment by oliverchang** [comment]
Not too familiar with vendoring in Go in general, but what benefit does this give us over just having go.mod/go.sum?

Is it just protecting against some library we depend on getting deleted at some point, or are there other benefits here?

**Comment by naveensrinivasan** [comment]
> Not too familiar with vendoring in Go in general, but what benefit does this give us over just having go.mod/go.sum?
> 
> Is it just protecting against some library we depend on getting deleted at some point, or are there other benefits here?

Other than that https://stackoverflow.com/a/67927672

**Pull request closed without merging**
