### PR TITLE
:seedling: Fix the go.mod with v2 upgrade

### LINKED ISSUE #711: Can't import scorecard
I believe go.mod need to be updated from:
```
module github.com/ossf/scorecard
```
to:
```
module github.com/ossf/scorecard/v2
```
To correspond to the v2.0.0 release, which indicates a breaking change in semver, which go uses for imports.
see: https://github.com/golang/go/issues/35732

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
bug fix

* **What is the current behavior?** (You can also link to an open issue here)
Fixes #711 

* **What is the new behavior (if this is a feature change)?**
The `go.mod` wasn't updated with the v2 upgrade.https://github.com/ossf/scorecard/issues/711

This fix will address the issue.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
None

* **Other information**:
None

### CODE REVIEW

**Comment by jeffmendoza** [comment]
Do all self-imports in code need to be changed to v2 as well? Not sure.

**Comment by naveensrinivasan** [comment]
> Do all self-imports in code need to be changed to v2 as well? Not sure.

Agreed, looks like every replacement would require a go.mod https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive

So we would need multiple modules. 

cc @azeemshaikh38

**Comment by azeemshaikh38** [comment]
> > Do all self-imports in code need to be changed to v2 as well? Not sure.
> 
> Agreed, looks like every replacement would require a go.mod https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive
> 
> So we would need multiple modules.
> 
> cc @azeemshaikh38

Looking at a Google repo, the way this seems to be done is by updating all references to self-imports: https://github.com/google/go-github/commit/05e95d3c51abdf832f9430209ccb46b494ac7be8#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6.

I would prefer this way in contrast to the `replace` directive to stay in sync with Google guidelines.

**Comment by naveensrinivasan** [comment]
Apologies for the large PR. This cannot be broken down into smaller chunks as it is changing the version across many files.

**Review by azeemshaikh38 — APPROVED** [review]
Thanks!

@jeffmendoza FYI

**Pull request merged**
