### PR TITLE
:sparkles:ci: drop trailing whitespaces

### PR DESCRIPTION
**Pull request by evverx**
This should help to prevent various linters from complaining about
trailing whitespaces when the file is copy-pasted to other repositories:
```
.github/workflows/scorecard-analysis.yml:2: trailing whitespace.
+on:
.github/workflows/scorecard-analysis.yml:18: trailing whitespace.
+
.github/workflows/scorecard-analysis.yml:40: trailing whitespace.
+
```

### CODE REVIEW

**Review by naveensrinivasan — APPROVED** [review]
Thanks

**Comment by naveensrinivasan** [comment]
@laurentsimon 👀 please

**Review by laurentsimon — APPROVED** [review]
Thank you!

**Pull request merged**
