### PR TITLE
:seedling: .github: Audit CodeQL egress with harden-runner

### PR DESCRIPTION
**Pull request by naveensrinivasan**
#### What kind of change does this PR introduce?
Included hard-runner to restrict egress traffic.

- [ ] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the new behavior (if this is a feature change)?**

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

NONE

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

```release-note
NONE
```

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@ossf/scorecard-maintainers  I would like to propose this change. Let me know if someone has a different opinion.

cc @varunsh-coder

**Comment by naveensrinivasan** [comment]
The license for hard-runner is https://github.com/step-security/harden-runner/blob/main/LICENSE

**Comment by varunsh-coder** [comment]
> The license for hard-runner is https://github.com/step-security/harden-runner/blob/main/LICENSE

Thanks @naveensrinivasan for trying it out. Let me know if you need any help adding it. Note: the Action uses an agent, and the agent also has the same license. 

https://github.com/step-security/agent/blob/main/LICENSE 

I am trying to make harden-runner an OSSF project. So do share feedback from using this, as those improvement ideas can be used in the OSSF project, if/when that gets thru...Thanks!

**Review by azeemshaikh38 — APPROVED** [review]
LGTM. @justaugustus @laurentsimon for a second opinion.

**Review by justaugustus — APPROVED** [review]
@naveensrinivasan -- Tweaked the PR title, since we're auditing egress, not blocking yet

**Pull request merged**
