### PR TITLE
📖 Modify the text to acknowledge GitHub != universe

### PR DESCRIPTION
**Pull request by david-a-wheeler**
There are many source repository hosting services (forges),
not just GitHub. This generalizes the requirements, e.g., from:

> Determines if the project's GitHub workflows follow the principle of least privilege.

to:

> Determines if the project's workflows follow the principle of least privilege.

Scorecard doesn't currently *implement* checks in most cases for
systems other than GitHub, so acknowledge that as a limitation, instead
of implying that it's the one true way to implement secure software.

Signed-off-by: David A. Wheeler <dwheeler@dwheeler.com>

### CODE REVIEW

**Review by azeemshaikh38 — COMMENTED** [review]
Run `make generate-docs`?

**Comment by david-a-wheeler** [comment]
> Run make generate-docs?

Some past commits didn't run `make generate-docs`. I'm afraid that if I run `make generate-docs` within this commit, it'll appear to add unrelated changes, possibly even leading to merge conflicts.

So I propose accepting this commit & other recent commits on the docs, *then* run a separate commit to `make generate-docs`. That'll have the same result with less intermediate pain.

**Comment by naveensrinivasan** [comment]
> > Run make generate-docs?
> 
> Some past commits didn't run `make generate-docs`. I'm afraid that if I run `make generate-docs` within this commit, it'll appear to add unrelated changes, possibly even leading to merge conflicts.
> 
> So I propose accepting this commit & other recent commits on the docs, _then_ run a separate commit to `make generate-docs`. That'll have the same result with less intermediate pain.

That sounds good to me. @azeemshaikh38 WDYT?

**Comment by naveensrinivasan** [comment]
> > > Run make generate-docs?
> > 
> > 
> > Some past commits didn't run `make generate-docs`. I'm afraid that if I run `make generate-docs` within this commit, it'll appear to add unrelated changes, possibly even leading to merge conflicts.
> > So I propose accepting this commit & other recent commits on the docs, _then_ run a separate commit to `make generate-docs`. That'll have the same result with less intermediate pain.
> 
> That sounds good to me. @azeemshaikh38 WDYT?

@azeemshaikh38 Ping

**Comment by azeemshaikh38** [comment]
> > > > Run make generate-docs?
> > > 
> > > 
> > > Some past commits didn't run `make generate-docs`. I'm afraid that if I run `make generate-docs` within this commit, it'll appear to add unrelated changes, possibly even leading to merge conflicts.
> > > So I propose accepting this commit & other recent commits on the docs, _then_ run a separate commit to `make generate-docs`. That'll have the same result with less intermediate pain.
> > 
> > 
> > That sounds good to me. @azeemshaikh38 WDYT?
> 
> @azeemshaikh38 Ping

SGTM.

**Review by naveensrinivasan — APPROVED** [review]

**Pull request merged**
