### PR TITLE
🌱 add the rest of Metal3 repos to the project list

### PR DESCRIPTION
**Pull request by tuminoid**
#### What kind of change does this PR introduce?

Adding the rest of the Metal3 repos to be scanned.

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

Only some Metal3 repos are in project list.

#### What is the new behavior (if this is a feature change)?**

All of the Metal3 repos are added to the project list.

#### Which issue(s) this PR fixes

Fixes #3777 

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

**Review by spencerschrock — APPROVED** [review]
Thanks. Can't merge since it's out of date, and "Allow edits and access to secrets by maintainers" isn't checked so can't do it myself.

I'll keep an eye out for you to click the "update branch" button

**Comment by tuminoid** [comment]
> I'll keep an eye out for you to click the "update branch" button

I've rebased it now.

**Comment by tuminoid** [comment]
Thank you!

**Comment by spencerschrock** [comment]
> Thank you!

Just an FYI, the next run starts 2024-01-15 02:00 UTC and should complete by 2024-01-22 02:00 UTC. So you should see that reflected in the API in ~11 days time.

**Pull request merged**
