### PR TITLE
:sparkles:CI-Check: add SemaphoreCI and Packit-as-a-Service

### PR DESCRIPTION
**Pull request by evverx**
to make it more likely for some projects to pass the check

https://semaphoreci.com/
https://github.com/marketplace/packit-as-a-service

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
Packit-as-a-service is not verified by GitHub, Is it OSS?
https://github.com/marketplace/packit-as-a-service

Also, https://semaphoreci.com/ is a paid service. 

@laurentsimon @azeemshaikh38  Your thoughts on this?

**Comment by laurentsimon** [comment]
I'm OK with adding these. Somewhat unrelated: to beef up the SAST check, we could list the SAST tool from the GitHub marketplace and add their name to the SAST check.

**Comment by evverx** [comment]
> Packit-as-a-service is not verified by GitHub, Is it OSS?

I'm pretty sure it is. Though I agree it would be great if it was verified. @mrc0mmand I wonder if it would  be possible to somehow ask the maintainers to verify it according to https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-apps?

> which projects use semaphoreci?

`systemd` and `systemd-stable` use it

**Comment by mrc0mmand** [comment]
> > Packit-as-a-service is not verified by GitHub, Is it OSS?
> 
> I'm pretty sure it is. Though I agree it would be great if it was verified. @mrc0mmand I wonder if it would be possible to somehow ask the maintainers to verify it according to https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges#for-github-apps?

I'll speak with Packit maintainers tomorrow to see what can be done.

**Comment by laurentsimon** [comment]
Thank you both for helping out!

**Comment by mrc0mmand** [comment]
Spoke with one of the Packit developers and, citing:
> that completely makes sense! We'll look into it

**Comment by evverx** [comment]
@mrc0mmand currently `scorecard` can't recognize CentoOS CI either (which is fine because it's a custom service). I wonder if there's a way to detect it somehow automatically? I think one option would be to add "Test" somewhere so that the name would look like "CentOS CI (Test Arch Linux + sanitizers)" but I'm not sure I like it. It isn't urgent or anything though :-)

**Comment by mrc0mmand** [comment]
> @mrc0mmand currently `scorecard` can't recognize CentoOS CI either (which is fine because it's a custom service). I wonder if there's a way to detect it somehow automatically? I think one option would be to add "Test" somewhere so that the name would look like "CentOS CI (Test Arch Linux + sanitizers)" but I'm not sure I like it. It isn't urgent or anything though :-)

I guess I could tweak the context of CentOS CI results to something like *CentOS CI Jenkins (...)*, since it's run in a Jenkins instance (and it feels less *forced* than the "Test" thingy). Also, it should match the pattern in `isTest()`.

**Comment by evverx** [comment]
"Jenkins" sounds better I have to admit :-) Anyway, with this PR merged scorecard should be able to cover all the CI services used by systemd except CentOS CI and Ubuntu CI and I think in theory it should be enough for systemd to pass that check 99% of the time I think. Let's just wait and see if this assumption is correct :-)

**Comment by laurentsimon** [comment]
probably also need to make the sting pattern matching case insensitive. wdut?

**Comment by evverx** [comment]
As far as I can see it already is. `strings.ToLower` is called at the top of `isTest`

**Comment by laurentsimon** [comment]
> As far as I can see it already is. `strings.ToLower` is called at the top of `isTest`

oops, my bad.

**Review by oliverchang — APPROVED** [review]
Thanks @evverx! This LGTM assuming there's no further objections from anyone else.

**Comment by evverx** [comment]
> I guess I could tweak the context of CentOS CI results to something like CentOS CI Jenkins (...), since it's run in a Jenkins instance (and it feels less forced than the "Test" thingy)

Looking at the bcc project I think I know how Jenkins can be detected automatically:
```diff
Author: Evgeny Vereshchagin <evvers@ya.ru>
Date:   Tue Nov 23 09:09:28 2021 +0000

    CI-Tests: look for test-related strings in target urls as well

    Apparently some projects like systemd and bcc put links (containing
    the word "Jenkins") to their Jenkins instances in target urls.

    https://buildbot.iovisor.org/jenkins/job/bcc-pr/1157/
    https://jenkins-systemd.apps.ocp.ci.centos.org/job/upstream-vagrant-archlinux-sanitizers/8288/

diff --git a/checks/ci_tests.go b/checks/ci_tests.go
index ec6c4ee..e1fd44a 100644
--- a/checks/ci_tests.go
+++ b/checks/ci_tests.go
@@ -100,7 +100,7 @@ func prHasSuccessStatus(pr *clients.PullRequest, c *checker.CheckRequest) (bool,
                if status.State != success {
                        continue
                }
-               if isTest(status.Context) {
+               if isTest(status.Context) || isTest(status.TargetURL) {
                        c.Dlogger.Debug3(&checker.LogMessage{
                                Path: status.URL,
                                Type: checker.FileTypeURL,
diff --git a/clients/githubrepo/statuses.go b/clients/githubrepo/statuses.go
index befe25e..b033ad8 100644
--- a/clients/githubrepo/statuses.go
+++ b/clients/githubrepo/statuses.go
@@ -50,9 +50,10 @@ func statusesFrom(data []*github.RepoStatus) []clients.Status {
        var statuses []clients.Status
        for _, status := range data {
                statuses = append(statuses, clients.Status{
-                       State:   status.GetState(),
-                       Context: status.GetContext(),
-                       URL:     status.GetURL(),
+                       State:     status.GetState(),
+                       Context:   status.GetContext(),
+                       URL:       status.GetURL(),
+                       TargetURL: status.GetTargetURL(),
                })
        }
        return statuses
diff --git a/clients/statuses.go b/clients/statuses.go
index 000cd68..21f5e89 100644
--- a/clients/statuses.go
+++ b/clients/statuses.go
@@ -16,7 +16,8 @@ package clients

 // Status for a Git object/ref.
 type Status struct {
-       State   string
-       Context string
-       URL     string
+       State     string
+       Context   string
+       URL       string
+       TargetURL string
 }
```
I can probably add `autopkgtest` to the list as well to cover Ubuntu CI! I'll send a PR once https://github.com/ossf/scorecard/pull/1335 is merged to avoid rebasing 5 PRs over and over again

**Comment by evverx** [comment]
With both those patches applied the bcc score increased from -1 to 8 in one fell swoop :-)
```
      "details": [
        "Debug: CI test found: pr: 3651, context: default: https://api.github.com/repos/iovisor/bcc/statuses/173857dc031db9fdbaa6d8d34ad143a664bddab8",
        "Debug: CI test found: pr: 3652, context: default: https://api.github.com/repos/iovisor/bcc/statuses/8ad3fe3fe5a5188e189993ef4587ab26bf16d26e",
        "Debug: merged PR without CI test: 3659",
        "Debug: CI test found: pr: 3661, context: default: https://api.github.com/repos/iovisor/bcc/statuses/2ec7b7c2492badd387e00cb869fb5cae06b0fef9",
        "Debug: CI test found: pr: 3662, context: default: https://api.github.com/repos/iovisor/bcc/statuses/531b698cdc2053f14bd07adf2a089e177dccebeb",
        "Debug: CI test found: pr: 3663, context: default: https://api.github.com/repos/iovisor/bcc/statuses/c8548475d9da3e99e35a66afb6b9bcf7985e0a19",
        "Debug: CI test found: pr: 3665, context: default: https://api.github.com/repos/iovisor/bcc/statuses/b271b8a688e04e65be04e2340c663910d9dc7782",
        "Debug: CI test found: pr: 3666, context: default: https://api.github.com/repos/iovisor/bcc/statuses/4fccf1cd55d094014e111296defe3ab0814f2c7e",
        "Debug: CI test found: pr: 3669, context: default: https://api.github.com/repos/iovisor/bcc/statuses/2133464fe9b92be51ec80e4db7fb23ff9e77c40e",
        "Debug: CI test found: pr: 3670, context: default: https://api.github.com/repos/iovisor/bcc/statuses/dc0c8788e49ca71d45697e9144b20b64fbe7a04b",
        "Debug: CI test found: pr: 3672, context: default: https://api.github.com/repos/iovisor/bcc/statuses/b4e1411766f4142fe8b44202472e9bbad684a994",
        "Debug: CI test found: pr: 3673, context: default: https://api.github.com/repos/iovisor/bcc/statuses/e9f140f0fea0ba2fcd9af9ec4ede1e957a25a1b1",
        "Debug: CI test found: pr: 3678, context: default: https://api.github.com/repos/iovisor/bcc/statuses/f6b162d55c8ed71665a99afa69d42fac0ed7f7e8",
        "Debug: CI test found: pr: 3683, context: default: https://api.github.com/repos/iovisor/bcc/statuses/bfa3b3807ef53e4cd1c9d392ec068e62914c79ec",
        "Debug: CI test found: pr: 3684, context: default: https://api.github.com/repos/iovisor/bcc/statuses/4ab17aec35e61edf8b4dc9bc14400e94d35c7ef5",
        "Debug: CI test found: pr: 3692, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4143493809",
        "Debug: merged PR without CI test: 3694",
        "Debug: CI test found: pr: 3695, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4173752711",
        "Debug: merged PR without CI test: 3700",
        "Debug: merged PR without CI test: 3703",
        "Debug: CI test found: pr: 3704, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4215392883",
        "Debug: CI test found: pr: 3707, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4233414592",
        "Debug: CI test found: pr: 3708, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4233025933",
        "Debug: CI test found: pr: 3710, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4245312441",
        "Debug: CI test found: pr: 3711, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4245618137",
        "Debug: CI test found: pr: 3712, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4245860482",
        "Debug: CI test found: pr: 3713, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4248079847",
        "Debug: CI test found: pr: 3714, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4261286814",
        "Debug: CI test found: pr: 3716, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4282219206",
        "Debug: CI test found: pr: 3721, context: github-actions: https://api.github.com/repos/iovisor/bcc/check-runs/4287369930"
      ],
      "score": 8,
      "reason": "26 out of 30 merged PRs checked by a CI test -- score normalized to 8",
      "name": "CI-Tests",
```

**Comment by oliverchang** [comment]
@naveensrinivasan  @laurentsimon any more concerns with this, or should we merge?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan  @laurentsimon any more concerns with this, or should we merge? 

I am good. Apologies for the delay. 

WDYT @laurentsimon?

**Comment by mrc0mmand** [comment]
A quick update: Packit is now a verified app in the GH marketplace: https://github.com/marketplace/packit-as-a-service (kudos to @csomh for taking care of this).

**Pull request merged**
