### PR TITLE
:bug: Fix golangci-lint issues

### LINKED ISSUE #1659: BUG - Fix golang CI issues
**Describe the bug**
Fix golang ci issues
```
Error: clients/cii_blob_client.go:22:1: Expected '\t', Found '\n' at clients/cii_blob_client.go[line 22,col 1] (gci)
[45](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:45)

[46](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:46)
^
[47](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:47)
Error: docs/checks/internal/reader.go:19:1: Expected '\t', Found '\n' at docs/checks/internal/reader.go[line 19,col 1] (gci)
[48](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:48)

[49](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:49)
^
[50](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:50)
Error: cron/worker/main.go:25:1: Expected '\t', Found '\n' at cron/worker/main.go[line 25,col 1] (gci)
[51](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:51)

[52](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:52)
^
[53](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:53)
Error: cron/config/config.go:19:1: Expected '\t', Found '\n' at cron/config/config.go[line 19,col 1] (gci)
[54](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:54)

[55](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:55)
^
[56](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:56)
Error: cron/data/blob.go:26:1: Expected '\t', Found '\n' at cron/data/blob.go[line 26,col 1] (gci)
[57](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:57)

[58](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:58)
^
[59](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:59)
Error: cron/format/json.go:21:1: Expected '\t', Found '\n' at cron/format/json.go[line 21,col 1] (gci)
[60](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:60)

[61](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:61)
^
[62](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:62)
Error: cron/pubsub/publisher.go:27:1: Expected '\t', Found '\n' at cron/pubsub/publisher.go[line 27,col 1] (gci)
[63](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:63)

[64](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:64)
^
[65](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:65)
Error: cron/pubsub/subscriber_gocloud.go:23:1: Expected '\t', Found '\n' at cron/pubsub/subscriber_gocloud.go[line 23,col 1] (gci)
[66](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:66)

[67](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:67)
^
[68](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:68)
make: *** [Makefile:58: check-linter] Error 1
[69](https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true#step:6:69)
Error: Process completed with exit code 2.
```

With the latest update of golang ci these issues have to be addressed. 

https://github.com/ossf/scorecard/runs/5248343538?check_suite_focus=true

### PR DESCRIPTION
**Pull request by r0mdau**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix #1659 

* **What is the current behavior?** (You can also link to an open issue here)
 #1659 

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

I started by updating the gci configuration in `.golangci.yml` regarding their [documentation](https://golangci-lint.run/usage/linters/#gci).

Then I executed this command to fix issues : 
```
golangci-lint run -c .golangci.yml --fix
```

### CODE REVIEW

**Review by naveensrinivasan — COMMENTED** [review]
Thanks, could you also please upgrade the golang ci to the latest version? This will make sure we aren't breaking when we upgrade. 


https://github.com/ossf/scorecard/pull/1658

**Review by naveensrinivasan — APPROVED** [review]
Thank you!

**Comment by r0mdau** [comment]
@naveensrinivasan I am pushing changes, sorry, this is not super clean, wait one minute

**Comment by r0mdau** [comment]
This commit should be the good one

**Pull request merged**
