### PR TITLE
✨  Add e2e tests using dedicated repo for pinned-dependencies check

### PR DESCRIPTION
**Pull request by laurentsimon**
* **Please check if the PR fulfills these requirements**
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
real-world repo.

* **What is the new behavior (if this is a feature change)?**
dedicated repo

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

### CODE REVIEW

**Comment by laurentsimon** [comment]
@naveensrinivasan how to I bypass the failing check? I've added empty files on purpose for unit tests.

**Comment by laurentsimon** [comment]
not sure what to do with the failing check happening (tracked in https://github.com/ossf/scorecard/issues/646)
```
protoc --go_out=../../../ cron/data/request.proto
/bin/bash: protoc: command not found
```
@azeemsgoogle @naveensrinivasan @inferno-chromium who can help me?

**Comment by azeemshaikh38** [comment]
> not sure what to do with the failing check happening (tracked in #646)
> 
> ```
> protoc --go_out=../../../ cron/data/request.proto
> /bin/bash: protoc: command not found
> ```
> 
> @azeemsgoogle @naveensrinivasan @inferno-chromium who can help me?

I found this which might help - https://lukasjoswiak.com/github-actions-protobuf/

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
Btw, how we do create a repo in ossf-tests? Could you add me there? I'd like to replace https://github.com/ossf/scorecard/blob/4d7fb5d7485a02521284e62c721112d59a5136e7/e2e/vulnerabilities_test.go#L66 

with a repo there instead.

**Comment by azeemshaikh38** [comment]
> Btw, how we do create a repo in ossf-tests? Could you add me there? I'd like to replace
> 
> https://github.com/ossf/scorecard/blob/4d7fb5d7485a02521284e62c721112d59a5136e7/e2e/vulnerabilities_test.go#L66
> 
> with a repo there instead.

Just added you as owner.

**Pull request merged**
