### PR TITLE
🌱 Use backlog and "help wanted" labels on issues/PRs to keep stale-bot away

### PR DESCRIPTION
**Pull request by pnacht**
#### What kind of change does this PR introduce?

Tells the stale bot that issues/PRs labelled "never stale" shouldn't be considered stale.

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

The stale bot will mark any issue or PR without activity as stale after some time. The exceptions are the issues and PRs with a few specific labels: 

- issues: `priority`, `bug` and `good first issue`
- PRs: `awaiting-approval` and `work-in-progress`

However, there are other types of issues (and maybe PRs) that should remain open indefinitely: these may be more "philosophical" questions regarding Scorecard (i.e. #3549 and #2483) or "wishlist" feature requests that require changes in other places (i.e. #10). 

#### What is the new behavior (if this is a feature change)?**

Issues and PRs can now be labelled as `never stale`. These issues will never be marked as stale or closed by the stale-bot. (A maintainer will still need to create these labels).

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

As discussed in https://github.com/ossf/scorecard/issues/2761#issuecomment-1817894945.

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

**Comment by spencerschrock** [comment]
Agree that having the author/interested party needing to constantly say "not stale" is bad. I think adding a generic `not stale` label is probably ok, but can see it being over-used and we would end up with a bunch of stale issues that are marked `not stale`.

So this seems like a triaging process, and the issue should really reflect the current state. In the case of your linked issue (#2761), it has support from one of the maintainers. Maybe we should have a `good idea` or `tentatively approved` or something label, which gets exempted instead.

**Comment by raghavkaul** [comment]
My 2c: The existing categories describe issues well, but we could be better about tagging proactively.

**Comment by spencerschrock** [comment]
> My 2c: The existing categories describe issues well, but we could be better about tagging proactively.

What label would you add to the issue in this case, and then to stale exemption list?

**Comment by raghavkaul** [comment]
Maybe I'd add `backlog` or `icebox` to indicate that an issue is low priority but still in the consideration as a feature with widespread acceptance that it should be in Scorecard.

**Comment by pnacht** [comment]
Just pushed a change adopting `icebox` and `help wanted`, for anything the team would like to see but doesn't have time to implement itself.

Also removed the label from PRs because I can't really think of a use-case there that doesn't fit into the existing labels.

**Comment by spencerschrock** [comment]
Is icebox a common term? I personally think it's a bit cryptic compared to backlog

**Comment by raghavkaul** [comment]
Backlog is more commonly used, sounds fine with me.

**Comment by pnacht** [comment]
Ah, I used "icebox" due to @raghavkaul's suggestion. The term isn't as widely used as backlog, but it [does exist](https://www.reddit.com/r/agile/comments/41204f/what_is_an_icebox/).

Also, "backlog" is a fairly overloaded term, and in some definitions it's "this is what we ARE going to work on" (in agile, the tasks that will be performed during a sprint are the "backlog" or "[sprint backlog](https://asana.com/resources/sprint-backlog)"... there's also "work backlog" which is the lower priority stuff).

Another term I've often seen used is "[backburner](https://scrumdictionary.com/term/back-burner/)".

**Comment by pnacht** [comment]
> I think another aspect of confusion is who "we" is here. And my understanding is the issue is something we'd be fine with but want the community to pickup. Which sounds like "help wanted" (although we need to change the description as it's currently "Extra attention is needed")
> 
> So is "backlog" for maintainers to do, and "help wanted" for anyone/community to do?

That could be an option, yes. Basically:
- "backlog/icebox/backburner" = "stuff maintainers want to do but don't have time for right now, maybe we'll get to it in the future"
- "help wanted" = "stuff that'd be nice-to-have but is pretty low priority, maintainers likely will never do this themselves, but it'd be great if you could do it!"

**Review by spencerschrock — APPROVED** [review]

**Pull request merged**
