### PR TITLE
✨ Use blob-based CII client

### LINKED ISSUE #1240: Feature: Improve `CII-Best-Practices-Badge` API access
Scorecard check for `CII-Best-Practices-Badge` makes a single HTTP request per repo. With our current scale of 1M repos, the cron job constantly receives 429 errors and is also affecting the CII Best Practices servers. To remediate this, will use the page-based API to pre-download the data into Google Cloud and access this instead - https://github.com/coreinfrastructure/best-practices-badge/blob/main/doc/best_practices.py

@david-a-wheeler FYI.

### PR DESCRIPTION
**Pull request by azeemshaikh38**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fixes #1240 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]

**Comment by david-a-wheeler** [comment]
LGTM!

The issue is, how often will you update the database download? Weekly, or at most daily, should be adequate.

**Comment by azeemshaikh38** [comment]
> LGTM!
> 
> The issue is, how often will you update the database download? Weekly, or at most daily, should be adequate.

As of now it'll happen monthly. I'm assuming the data doesn't change too often?

**Comment by david-a-wheeler** [comment]
Data changes far more often, but I think you just want to know "is a project pursuing a badge" & "does it have one".

Every day about 1-2 projects join, and occasionally a project gets a badge. Waiting up to a whole month to update seems very long.

I think a weekly download, at least for now, would be the best pace.

**Comment by azeemshaikh38** [comment]
> Data changes far more often, but I think you just want to know "is a project pursuing a badge" & "does it have one".
> 
> Every day about 1-2 projects join, and occasionally a project gets a badge. Waiting up to a whole month to update seems very long.
> 
> I think a weekly download, at least for now, would be the best pace.

Updated to run weekly in #1309

**Pull request merged**
