### PR TITLE
Add top 200 for all langs from criticality score repo.

### PR DESCRIPTION
**Pull request by inferno-chromium**
From https://github.com/ossf/criticality_score#public-data
and combine with existing projects list.

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
NA

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Adds top 200 for each lang in cron/projects.txt

* **What is the current behavior?** (You can also link to an open issue here)
Small sample list.

* **What is the new behavior (if this is a feature change)?**
Expand to important projects.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
Cool! Will this not cause running out of GitHub API calls?

**Comment by inferno-chromium** [comment]
> Cool! Will this not cause running out of GitHub API calls?

We have multiple github tokens, and scorecard can bounce between them (or wait if we run out of api quota till it is restored again). we might not finish in a day, so might have to reduce cron freq, can try it out. Anyway, this system needs to scale, so we will keep trying different things.

**Comment by naveensrinivasan** [comment]
> > Cool! Will this not cause running out of GitHub API calls?
> 
> We have multiple github tokens, and scorecard can bounce between them (or wait if we run out of api quota till it is restored again). we might not finish in a day, so might have to reduce cron freq, can try it out. Anyway, this system needs to scale, so we will keep trying different things.

Sounds good. I would like to be part of scaling it :)

**Review by naveensrinivasan — APPROVED** [review]

**Comment by naveensrinivasan** [comment]
What was the source for this list?

**Comment by inferno-chromium** [comment]
> What was the source for this list?

https://github.com/ossf/criticality_score#public-data

**Pull request merged**
