### PR TITLE
:seedling: Fix failing e2e tests

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  Bug Fix

* **What is the current behavior?** (You can also link to an open issue here)
   Failing e2e tests

* **What is the new behavior (if this is a feature change)?**

    The packaging docker image for scorecard has been removed from github
    workflow to gcr.io.

    This was causing the e2e check failing.

    This fix will remove that check and address the failing e2e.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
  None

* **Other information**:
  None

### CODE REVIEW

**Review by inferno-chromium — COMMENTED** [review]
Slightly worried here, so will let @azeemsgoogle @azeemshaikh38 review this. we might forget to reenable this, so lets see if we can fix it somehow.

**Comment by naveensrinivasan** [comment]
> Slightly worried here, so will let @azeemsgoogle @azeemshaikh38 review this. we might forget to reenable this, so lets see if we can fix it somehow.

We will need to have a GitHub workflow with docker push. TBH I find that not a valid check. As a project, we don't use GitHub action to do any packaging.

**Comment by naveensrinivasan** [comment]
Cannot merge any PR's till we make a decision for this.

**Review by inferno-chromium — APPROVED** [review]
Ah there is a test already for apache/orc, then definitely fine to remove scorecard one.

**Pull request merged**
