### PR TITLE
:sparkles: setup-python not required by pypa/gh-action-pypi-publish

### PR DESCRIPTION
**Pull request by sethmlarson**
Signed-off-by: Seth Michael Larson <sethmichaellarson@gmail.com>

#### What kind of change does this PR introduce?

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

Requires `setup-python` to be used for publish GitHub Action jobs needlessly.

#### What is the new behavior (if this is a feature change)?**

`setup-python` won't be required by the job.

#### Which issue(s) this PR fixes

Fixes https://github.com/ossf/scorecard/issues/2196

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

**Review by naveensrinivasan — COMMENTED** [review]
Thank you! Could you please add some tests?

**Comment by sethmlarson** [comment]
@naveensrinivasan Unfortunately don't have time right now and won't for a while. Should I close this PR or leave for others to pick up?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan Unfortunately don't have time right now and won't for a while. Should I close this PR or leave for others to pick up?

I understand! I would suggest leaving it open. Thanks!

**Comment by Spikebady** [comment]
238231

**Comment by laurentsimon** [comment]
@spencerschrock @raghavkaul are you interested in finishing up this PR?

**Comment by spencerschrock** [comment]
I can finish it up. I'll send a PR with tests to @sethmlarson 's branch, and it should trickle into this PR once merged.

**Comment by spencerschrock** [comment]
Just to surface comments from the other PR:
> The function already had tests in the wrong place.
> Moved it to the right place and added new tests for the `pypa/gh-action-pypi-publish` action.

**Comment by laurentsimon** [comment]
Ping us when it's ready for review. Thanks

**Comment by spencerschrock** [comment]
@laurentsimon It should be ready for review already. I believe the added tests address @naveensrinivasan 's original comments.

**Review by laurentsimon — APPROVED** [review]
Thanks!

**Pull request merged**
