### PR TITLE
✨ Add cron github projects

### PR DESCRIPTION
**Pull request by laurentsimon**
…iation repo

* **Please check if the PR fulfills these requirements**
- [] Tests for the changes have been added (for bug fixes / features)
- [X] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
update

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
1) add more critical projects, 2) sort the entries, 3) add test remediation project

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

* **Other information**:

### CODE REVIEW

**Review by azeemshaikh38 — CHANGES_REQUESTED** [review]
Why have some projects been deleted? For e.g, I see `tensorflow/tensorflow` has been deleted.

**Comment by laurentsimon** [comment]
> Why have some projects been deleted? For e.g, I see `tensorflow/tensorflow` has been deleted.

my bad. I inadvertently ran `uniq -u` instead of `uniq`. Good catch! Thanks.

**Review by azeemshaikh38 — CHANGES_REQUESTED** [review]
Hmm, this is super hard to review. I'm curious, why not just add all the new ones to the end of the file to make this easier?

**Comment by naveensrinivasan** [comment]
> Hmm, this is super hard to review. I'm curious, why not just add all the new ones to the end of the file to make this easier?

I agree. Also how many new repo's are being added? Now that we are already having issues with scaling and reliability can this wait?

**Comment by laurentsimon** [comment]
I've added about 50. I basically added the 100 most critical repos according the the criticality score, then removed duplicates.
You're right it's hard to tell the difference. You can run `cat projects.txt | sort | uniq | tee _some_file_` on the existing repo. Then `diff _some_file_ projects_in_this_commit.txt`

**Review by azeemshaikh38 — APPROVED** [review]

**Pull request merged**
