### PR TITLE
:sparkles:Add LGTM to the SAST check

### PR DESCRIPTION
**Pull request by evverx**
According to https://github.com/apps/lgtm-com
"LGTM is a code analysis platform for identifying vulnerabilities early and preventing
them from reaching production". It's used by `systemd`, `lxc` and a lot of other large
open source projects. The check is
still kind of broken in the sense that it fails to detect
projects where every PR is analyzed by LGTM before getting merged
but it's better than nothing I guess.

### CODE REVIEW

**Review by naveensrinivasan — APPROVED** [review]
Thanks, @evverx! 

@olivekl Could you please review?

**Comment by evverx** [comment]
I'm not sure what `TestSARIFOutput` is but judging by https://github.com/ossf/scorecard/runs/4146238436?check_suite_focus=true it seems to have been failing since the latest commit was merged so I don't think it has anything to do with this PR.

**Review by azeemshaikh38 — APPROVED** [review]
Thanks!

**Comment by laurentsimon** [comment]
> I'm not sure what `TestSARIFOutput` is but judging by https://github.com/ossf/scorecard/runs/4146238436?check_suite_focus=true it seems to have been failing since the latest commit was merged so I don't think it has anything to do with this PR.

Thanks. I've send a PR to fix it https://github.com/ossf/scorecard/pull/1233

**Comment by laurentsimon** [comment]
> According to https://github.com/apps/lgtm-com "LGTM is a code analysis platform for identifying vulnerabilities early and preventing them from reaching production". It's used by `systemd`, `lxc` and a lot of other large open source projects. The check is still kind of broken in the sense that it fails to detect projects where every PR is analyzed by LGTM before getting merged but it's better than nothing I guess.

Can you elaborate? Function `sastToolInCheckRuns` does list merged PRs and look for `Slug`, see https://github.com/ossf/scorecard/blob/main/checks/sast.go#L138 Is this insufficient for LGTM? Is there some improvement we should make?

**Comment by evverx** [comment]
> Is this insufficient for LGTM?

I'm not sure. I need to figure out why `scorecard` says that "23 commits out of 30 are checked with a SAST tool". It could be it has something to do with "neutral" checks where the source code wasn't changed and LGTM was skipped in a way.

**Comment by laurentsimon** [comment]
> > Is this insufficient for LGTM?
> 
> I'm not sure. I need to figure out why `scorecard` says that "23 commits out of 30 are checked with a SAST tool". It could be it has something to do with "neutral" checks where the source code wasn't changed and LGTM was skipped in a way.

Thanks. Let's not block this PR on this problem. Can you create a tracking issue for it so we don't forget? If you're interested in looking into, help is appreciated!

**Review by laurentsimon — APPROVED** [review]

**Comment by evverx** [comment]
Looks like in PRs like https://github.com/systemd/systemd/pull/21266 the status of LGTM is "neutral" because "LGTM.com did not detect changes to any C/C++ files". It can be fixed by not skipping PRs where `cr.Conclusion` is neutral:
```diff
+                       if cr.Conclusion != "success" && cr.Conclusion != "neutral" {
                                continue
                        }
```
With that patch applied `scorecard` says that "29 commits out of 30 are checked with a SAST tool", which is correct because apparently in https://github.com/systemd/systemd/pull/21266 LGTM got lost somehow. Though I'm not sure flukes like that should affect the aggregate score.

**Comment by laurentsimon** [comment]
> Looks like in PRs like [systemd/systemd#21266](https://github.com/systemd/systemd/pull/21266) the status of LGTM is "neutral" because "LGTM.com did not detect changes to any C/C++ files". It can be fixed by not skipping PRs where `cr.Conclusion` is neutral:
> 
> ```diff
> +                       if cr.Conclusion != "success" && cr.Conclusion != "neutral" {
>                                 continue
>                         }
> ```
> 
> With that patch applied `scorecard` says that "29 commits out of 30 are checked with a SAST tool", which is correct because apparently in [systemd/systemd#21268](https://github.com/systemd/systemd/pull/21268) LGTM got lost somehow. Though I'm not sure flukes like that should affect the aggregate score.

That sounds good. Please send us a PR and cc me on it, I'll LGTM it.

**Comment by laurentsimon** [comment]
This PR is ready to merge code-wise. @olivekl we only need your ack for the documentation.

**Review by olivekl — APPROVED** [review]
LGTM! Thanks, @evverx!

**Comment by laurentsimon** [comment]
> LGTM! Thanks, @evverx!

Thanks.

**Pull request merged**
