### PR TITLE
🐛 CI-Tests: no longer fail if there are no check suites

### PR DESCRIPTION
**Pull request by evverx**
In PRs like https://github.com/iovisor/bcc/pull/3626 no check suites
are triggered:
```
$ curl --silent  -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/iovisor/bcc/commits/3fcf0f1b5862ff2c5908723b38b57c5d1c97c1cf/check-runs
{
  "total_count": 0,
  "check_runs": [

  ]
}
```
```
 curl --silent  -H "Accept: application/vnd.github.v3+json"   https://api.github.com/repos/iovisor/bcc/commits/3fcf0f1b5862ff2c5908723b38b57c5d1c97c1cf/check-suites
{
  "total_count": 0,
  "check_suites": [

  ]
}
```
The check should just keep going because "statuses" still can be
triggered so it should use them instead

Closes https://github.com/ossf/scorecard/issues/1285

### CODE REVIEW

**Comment by evverx** [comment]
FWIW I think this check should switch from `check-runs` to `check-suites` (as discussed in https://github.com/ossf/scorecard/issues/1322) but until then it shouldn't fail when there're no check runs (it shouldn't fail when there're no check suites either though :-))

**Review by laurentsimon — APPROVED** [review]
LGTM, thanks. cc @azeemsgoogle: can you confirm the `crs == nil` was not intentional ?

**Comment by evverx** [comment]
FWIW I don't think it can be intentional because because of that check projects with no tests get `-1` instead of `0` and I don't think that's correct.

**Comment by laurentsimon** [comment]
@naveensrinivasan @azeemsgoogle the e2e tests are failing because of the OSV check. Has anything changed recently? This PR does not touch the OSV/Vulnerabilities check.

**Comment by naveensrinivasan** [comment]
It is failing on 
```
• Failure [12.665 seconds]
323
E2E TEST:Fuzzing
324
/home/runner/work/scorecard/scorecard/e2e/fuzzing_test.go:29
325
  E2E TEST:Validating use of fuzzing tools
326
  /home/runner/work/scorecard/scorecard/e2e/fuzzing_test.go:30
327
    Should return use of OSS-Fuzz [It]
328
    /home/runner/work/scorecard/scorecard/e2e/fuzzing_test.go:31
329

330
    Expected
331
        <bool>: false
332
    to be true
333

334
    /home/runner/work/scorecard/scorecard/e2e/fuzzing_test.go:55
335
------------------------------
336
E2E TEST:Contributors E2E TEST:Validating project contributors 
337
  Should return valid project contributors
338
  /home/runner/work/scorecard/scorecard/e2e/contributors_test.go:31
339
•
340

341
Summarizing 1 Failure:
342

343
[Fail] E2E TEST:Fuzzing E2E TEST:Validating use of fuzzing tools [It] Should return use of OSS-Fuzz
```

**Comment by azeemshaikh38** [comment]
> 

+1. I think its an overall improvement to return 0 score over -1, so this PR LGTM.

**Pull request merged**
