### PR TITLE
:sparkles: Migrate to v4

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**
  v4 release 

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
Thanks.

**Review by azeemshaikh38 — APPROVED** [review]
Thanks! I have disabled auto-merge for now though. This needs to be submitted after we have cut the release right?

**Comment by naveensrinivasan** [comment]
> Thanks! I have disabled auto-merge for now though. This needs to be submitted after we have cut the release right?

Yes! after we have the v4 tag. Making any changes I will have to redo this again which is painful.

**Comment by naveensrinivasan** [comment]
When are we planning to do the v4 tag?

**Comment by azeemshaikh38** [comment]
> When are we planning to do the v4 tag?

Mostly mid-Jan. @laurentsimon to confirm.

**Comment by laurentsimon** [comment]
> > When are we planning to do the v4 tag?
> 
> Mostly mid-Jan. @laurentsimon to confirm.

we don't need to wait for the v4 tag. In fact, if we tag v4, the release will be broken because the tags will say v4 but the code will say v3. This is the problem that happened last time, right?

The HEAD code can be anything and does not affect users of the latest v3.x.y.

So we can merge this now.

**Comment by naveensrinivasan** [comment]
if that 

> > > When are we planning to do the v4 tag?
> > 
> > 
> > Mostly mid-Jan. @laurentsimon to confirm.
> 
> we don't need to wait for the v4 tag. In fact, if we tag v4, the release will be broken because the tags will say v4 but the code will say v3. This is the problem that happened last time, right?
> 
> The HEAD code can be anything and does not affect users of the latest v3.x.y.
> 
> So we can merge this now.

If that is the case then we would have to disable the `goreleaser check` as it will look for the `v3` at this branch.

**Comment by laurentsimon** [comment]
> if that
> 
> > > > When are we planning to do the v4 tag?
> > > 
> > > 
> > > Mostly mid-Jan. @laurentsimon to confirm.
> > 
> > 
> > we don't need to wait for the v4 tag. In fact, if we tag v4, the release will be broken because the tags will say v4 but the code will say v3. This is the problem that happened last time, right?
> > The HEAD code can be anything and does not affect users of the latest v3.x.y.
> > So we can merge this now.
> 
> If that is the case then we would have to disable the `goreleaser check` as it will look for the `v3` at this branch.

what is this check? Validaion check?

**Comment by naveensrinivasan** [comment]
> > if that
> > > > > When are we planning to do the v4 tag?
> > > > 
> > > > 
> > > > Mostly mid-Jan. @laurentsimon to confirm.
> > > 
> > > 
> > > we don't need to wait for the v4 tag. In fact, if we tag v4, the release will be broken because the tags will say v4 but the code will say v3. This is the problem that happened last time, right?
> > > The HEAD code can be anything and does not affect users of the latest v3.x.y.
> > > So we can merge this now.
> > 
> > 
> > If that is the case then we would have to disable the `goreleaser check` as it will look for the `v3` at this branch.
> 
> what is this check? Validation check?

`build-releaser`

**Comment by naveensrinivasan** [comment]
> > > > If that is the case then we would have to disable the `goreleaser check` as it will look for the `v3` at this branch.
> > > 
> > > 
> > > what is this check? Validation check?
> > 
> > 
> > `build-releaser`
> 
> this file https://github.com/ossf/scorecard/blob/main/.github/workflows/goreleaser.yaml?

https://github.com/ossf/scorecard/blob/192ae4d18fbaaeb7d2510b1116c26c817825e210/Makefile#L142

**Comment by naveensrinivasan** [comment]
I am going to remove this as part of this PR and then later add it back.

@azeemshaikh38 / @laurentsimon Thoughts?

**Comment by azeemshaikh38** [comment]
> I am going to remove this as part of this PR and then later add it back.
> 
> @azeemshaikh38 / @laurentsimon Thoughts?

SGTM

**Comment by naveensrinivasan** [comment]
> > I am going to remove this as part of this PR and then later add it back.
> > @azeemshaikh38 / @laurentsimon Thoughts?
> 
> SGTM

Thanks!

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 @laurentsimon any idea as to why is this build failing? It is not failing locally for me.

**Comment by laurentsimon** [comment]
> > I am going to remove this as part of this PR and then later add it back.
> > @azeemshaikh38 / @laurentsimon Thoughts?
> 
> SGTM

Same here, sgtm. Thanks @naveensrinivasan for the explanation

**Comment by laurentsimon** [comment]
`github.com/onsi/gomega@v1.16.0` not present in go.sum. Not sure why it's suddenly needed. Is your go.sum different from the committed to the repo?

**Comment by naveensrinivasan** [comment]
> `github.com/onsi/gomega@v1.16.0` not present in go.sum. Not sure why it's suddenly needed. Is your go.sum different from the committed to the repo?

No, it isn't. Can you try it locally and let me know if you are seeing any difference? Or are you able to build it?

**Comment by laurentsimon** [comment]
> > `github.com/onsi/gomega@v1.16.0` not present in go.sum. Not sure why it's suddenly needed. Is your go.sum different from the committed to the repo?
> 
> No, it isn't. Can you try it locally and let me know if you are seeing any difference? Or are you able to build it?

`make build-scorecard` worked. I use `$go version: go version go1.17 linux/amd64`

**Comment by laurentsimon** [comment]
@naveensrinivasan any luck on this PR?

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan any luck on this PR?

Nope!

**Comment by azeemshaikh38** [comment]
@naveensrinivasan fyi I'm adding some commits to this PR to get the build to pass.

**Pull request merged**
