### PR TITLE
:seedling: Don't close stale issues explicitly

### PR DESCRIPTION
**Pull request by spencerschrock**
Issues are still getting closed after https://github.com/ossf/scorecard/pull/3493. I assume there's a default value being used somewhere.

#### What kind of change does this PR introduce?

ci fix

- [X] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?
Issues are still getting closed (like #2614), even though #3493 was merged.

#### What is the new behavior (if this is a feature change)?**
`days-before-issue-close` is explicitly marked `-1` to disable auto-close.

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes
NONE

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the `release-note`

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note

```

### CODE REVIEW

**Review by afmarcum — APPROVED** [review]
Looks good. Thanks for updating the stale message as well.

**Comment by evverx** [comment]
Just out of curiosity I wonder why the "stale" label is needed? It's just that I received about 50 notification from GitHub saying that some scorecard issues got stale and I'm not sure how useful it is (to people reporting issues at least). If that label leads to closing issues like that anyway (unless someone artificially bumps them) it's almost the same as closing them automatically.

**Comment by spencerschrock** [comment]
> Just out of curiosity I wonder why the "stale" label is needed? It's just that I received about 50 notification from GitHub saying that some scorecard issues got stale and I'm not sure how useful it is (to people reporting issues at least). If that label leads to closing issues like that anyway (unless someone artificially bumps them) it's almost the same as closing them automatically.

The workflow predates my time on the project, but here's the value I get out of it (others can chime in):

1. a reminder about issues that have slipped through my emails
2. a gentle nudge if we're waiting on the author (although usually the staleness is on our side)


The label itself, not sure it provides a great value, but can be used in searches / filters.

I value staleness / auto-close a lot more on the PRs for the same reasons.

**Comment by evverx** [comment]
Got it. Thanks

I agree that it probably makes sense to bump PRs and post comments where authors disappear without replying. I'm not sure about issues though. The stale comments there fill out inboxes and aren't actionable to most people involved probably. Either way I unsubscribed from scorecard notifications so it's no longer an issue :-)

**Pull request merged**
