### PR TITLE
🐛  Fix the Code review merged by user reference

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
  Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
  Fixes the https://github.com/ossf/scorecard/issues/1260

* **What is the new behavior (if this is a feature change)?**
  Fixes the https://github.com/ossf/scorecard/issues/1260

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
  None

* **Other information**:

### CODE REVIEW

**Comment by laurentsimon** [comment]
I think this is a draft. Let me know when you need a review.

**Comment by naveensrinivasan** [comment]
> I think this is a draft. Let me know when you need a review.

Why do you think this is a draft? What else is missing?

**Comment by laurentsimon** [comment]
> > I think this is a draft. Let me know when you need a review.
> 
> Why do you think this is a draft? What else is missing?

I don't see changes to the Code-Review check itself, so I'm assuming it's not aware of the new `MergedBy` value...

**Comment by laurentsimon** [comment]
Before merging this PR, let's be sure it does not break an earlier fix https://github.com/ossf/scorecard/issues/895

**Comment by azeemshaikh38** [comment]
are we ready to submit this PR or is there anything pending here?

**Comment by laurentsimon** [comment]
can we add unit tests to verify what the PR fixes? I think we're also missing some checks for previous PR https://github.com/ossf/scorecard/pull/1272#issuecomment-970351591.
I'm just afraid to break other changes we've made... since we don't have unit tests for it. If we break, we go in circles :-)
wdut?

**Comment by azeemshaikh38** [comment]
> can we add unit tests to verify what the PR fixes? I think we're also missing some checks for previous PR [#1272 (comment)](https://github.com/ossf/scorecard/pull/1272#issuecomment-970351591). I'm just afraid to break other changes we've made... since we don't have unit tests for it. If we break, we go in circles :-) wdut?

+1 to adding unit tests. No rush on submitting this PR. Just trying to reduce the number of open issues so wanted to check if this PR can close the linked issue.

**Comment by naveensrinivasan** [comment]
Agreed on the unit tests!

**Pull request closed without merging**
