### PR TITLE
:seedling: Update golangci version to 1.39

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Update the lint

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

  * Upgrade the golangci version to 1.37

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
No

### CODE REVIEW

**Review by azeemshaikh38 — APPROVED** [review]

**Review by azeemshaikh38 — CHANGES_REQUESTED** [review]
Tests are failing

**Comment by naveensrinivasan** [comment]
> Tests are failing

I know working on that. 👍

**Comment by naveensrinivasan** [comment]
> Tests are failing

Should be good now!

**Comment by naveensrinivasan** [comment]
> > Tests are failing
> 
> Should be good now!

Still failing 🤦  with Git issues

**Comment by naveensrinivasan** [comment]
The build issue has been fixed.

**Comment by naveensrinivasan** [comment]
> Tests are failing

Not it is addressed.

**Review by azeemshaikh38 — APPROVED** [review]

**Pull request merged**
