### PR TITLE
Testing - Slash command

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
N/A

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Fix for ok-to-test URL

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@dlorenc  We have `ok-to-test` working without exposing the secrets with `actions`

**Comment by naveensrinivasan** [comment]
ping @inferno-chromium

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
