### PR TITLE
Feature - Serve json response in http

### PR DESCRIPTION
**Pull request by naveensrinivasan**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
Not yet

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature to serve `json` over HTTP.

* **What is the current behavior?** (You can also link to an open issue here)
Serve's text over HTTP

* **What is the new behavior (if this is a feature change)?**
Server's json over HTTP. Utilize this HTTP endpoint to do `cron` jobs https://github.com/ossf/scorecard/blob/main/cron/projects.txt which would easier to scale.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
None

* **Other information**:

Tests with httpie
```
http --json  http://localhost:8080\?repo\=github.com/ossf/scorecard

{
    "Checks": [
        {
            "CheckName": "SAST",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        },
        {
            "CheckName": "Fuzzing",
            "Confidence": 10,
            "Details": null,
            "Pass": false
        },
        {
            "CheckName": "CII-Best-Practices",
            "Confidence": 10,
            "Details": null,
            "Pass": false
        },
        {
            "CheckName": "Security-Policy",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        },
        {
            "CheckName": "Signed-Releases",
            "Confidence": 10,
            "Details": null,
            "Pass": false
        },
        {
            "CheckName": "Frozen-Deps",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        },
        {
            "CheckName": "Signed-Tags",
            "Confidence": 10,
            "Details": null,
            "Pass": false
        },
        {
            "CheckName": "Packaging",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        },
        {
            "CheckName": "Branch-Protection",
            "Confidence": 0,
            "Details": null,
            "Pass": false
        },
        {
            "CheckName": "Contributors",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        },
        {
            "CheckName": "CI-Tests",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        },
        {
            "CheckName": "Code-Review",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        },
        {
            "CheckName": "Active",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        },
        {
            "CheckName": "Pull-Requests",
            "Confidence": 10,
            "Details": null,
            "Pass": true
        }
    ],
    "Date": "2021-02-14",
    "Repo": "github.com/ossf/scorecard"
}
```

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
ah, i should have seen this auto-merge. @naveensrinivasan fyi on these review changes, can do in any other cl.

**Comment by naveensrinivasan** [comment]
> ah, i should have seen this auto-merge. @naveensrinivasan fyi on these review changes, can do in any other cl.

No more auto-merge, I think that would solve the problem. Also, if you are looking for a change, then `request for a change`, will prevent auto merging

**Comment by inferno-chromium** [comment]
> > ah, i should have seen this auto-merge. @naveensrinivasan fyi on these review changes, can do in any other cl.
> 
> No more auto-merge, I think that would solve the problem. Also, if you are looking for a change, then `request for a change`, will prevent auto merging

Sounds good, lets just remove auto-merge. for small things, i dont like request changes, since it save me a a review iteration :)

**Comment by naveensrinivasan** [comment]
> > > ah, i should have seen this auto-merge. @naveensrinivasan fyi on these review changes, can do in any other cl.
> > 
> > 
> > No more auto-merge, I think that would solve the problem. Also, if you are looking for a change, then `request for a change`, will prevent auto merging
> 
> Sounds good, lets just remove auto-merge. for small things, i dont like request changes, since it save me a a review iteration :)

Agreed! Thanks

**Pull request merged**
