### PR TITLE
🌱  Add some more projects to be scanned in the cron 

### PR DESCRIPTION
**Pull request by katzj**
#### What kind of change does this PR introduce?

Infrastructure

- [✅] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the new behavior (if this is a feature change)?**

This adds projects to the weekly cron job

- [N/A] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

NONE

#### Does this PR introduce a user-facing change?

NONE

### CODE REVIEW

**Review by spencerschrock — CHANGES_REQUESTED** [review]
Similar to #3732, i'm going to temporarily hold this.  We should have the quota for both, but I still want to control when. It's on my list of things to do

**Comment by katzj** [comment]
Rebased my branch 👍 ✅

**Comment by spencerschrock** [comment]
can you run `make add-projects` and commit the changes? I'm seeing duplicates.
e.g. "github.com/gitlabphp/client," vs "github.com/GitLabPHP/Client" which is already in the list

For the future: I'll add this to the documentation somewhere and make the CI fail if it's not done.

**Comment by katzj** [comment]
Done ✅

**Comment by spencerschrock** [comment]
Thanks @katzj sorry for the back and forth

**Pull request merged**
