### PR TITLE
:book: governance: Adopt Scorecard project charter

### PR DESCRIPTION
**Pull request by justaugustus**
#### What kind of change does this PR introduce?

This PR introduces the Scorecard project charter, which has been approved by @ossf/scorecard-maintainers and adopted on 2024-04-24.

The project charter is included both in markdown and PDF formats.
- PDF: direct export from the finalized charter in Google Docs
- Markdown: exported from the finalized charter in Google Docs --> `pandoc` conversion to markdown --> manual formatting cleanups from me

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### Does this PR introduce a user-facing change?

For user-facing changes, please add a concise, human-readable release note to
the release-note

(In particular, describe what changes users might need to make in their
application as a result of this pull request.)

```release-note
NONE
```

### CODE REVIEW

**Comment by spencerschrock** [comment]
Do we need the PDF? it's just going to fall out of date in my opinion

**Review by spencerschrock — APPROVED** [review]
LGTM, but seems like something we would want multiple approvals on, so disabled auto-merge.

**Comment by justaugustus** [comment]
> Do we need the PDF? it's just going to fall out of date in my opinion

Discussed with @spencerschrock via DM, but carrying over here for visibility:
PDF provides a simple way for folks that may not be as technically inclined to download or reference the charter.
While this does create some opportunity for drift, the charter should be slow-moving with faster moving changes to happen within operational documentation.

**Comment by justaugustus** [comment]
> LGTM, but seems like something we would want multiple approvals on, so disabled auto-merge.

n.b. the merge of the charter is merely a formality, IMO.
The live document was already approved by us before shipping to LF Legal for execution.

**Review by raghavkaul — APPROVED** [review]
Looks good to merge!

**Pull request merged**
