### PR TITLE
:seedling: Fix maintainer activity upto last year

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Fixes https://github.com/ossf/scorecard/issues/2160

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
Thank. Hope this does not increase API usage too much.

**Review by azeemshaikh38 — CHANGES_REQUESTED** [review]
Could we hold off on these changes? This would completely change the output displayed on deps.dev so would be good to do a bit of analysis before merging this in. One simple analysis might be to use the RawData dumped out for 1M+ repos and get an histogram of last updated activity across the ecosystem. It should quickly tell us how changing to 1year will reflect on deps.dev. What do folks think?

**Comment by naveensrinivasan** [comment]
> Could we hold off on these changes? This would completely change the output displayed on deps.dev so would be good to do a bit of analysis before merging this in. One simple analysis might be to use the RawData dumped out for 1M+ repos and get an histogram of last updated activity across the ecosystem. It should quickly tell us how changing to 1year will reflect on deps.dev. What do folks think?

Sounds good. 

On a different note, Can we expose the raw data in the scorecards API? We have it in the bucket.

**Comment by azeemshaikh38** [comment]
> On a different note, Can we expose the raw data in the scorecards API? We have it in the bucket.

I don't think its in a state to be made public yet - some checks are yet to be migrated to raw data and we don't have a clearly defined schema for the results. Probably best to wait till we work these out.

**Pull request closed without merging**
