### PR TITLE
🐛 Ignore nil values in Branch-Protection check

### PR DESCRIPTION
**Pull request by azeemshaikh38**
* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Part of #1242.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
LGTM, thanks for the quick fix.
One question I have: when we ignore some setting, shall we add a 0 score to `scores` array? Otherwise the score won't see a difference when we run with or without admin token.

**Comment by azeemshaikh38** [comment]
> LGTM, thanks for the quick fix. One question I have: when we ignore some setting, shall we add a 0 score to `scores` array? Otherwise the score won't see a difference when we run with or without admin token.

Not sure what you mean. The scores array collects scores *across* branches. But each branch only has a single score int. I have refactored the `branch_protection` check a bit more. Take a look and let me know.

**Comment by laurentsimon** [comment]
> > LGTM, thanks for the quick fix. One question I have: when we ignore some setting, shall we add a 0 score to `scores` array? Otherwise the score won't see a difference when we run with or without admin token.
> 
> Not sure what you mean. The scores array collects scores _across_ branches. But each branch only has a single score int. I have refactored the `branch_protection` check a bit more. Take a look and let me know.

If run with admin token, there will be more settings we check for. I think this this means that when run with admin token, the overall score would drop (compared to a non-admin run) if all the settings that need admin settings are disabled

**Comment by laurentsimon** [comment]
do you know if it fixes both https://github.com/ossf/scorecard/issues/1247 and https://github.com/ossf/scorecard/issues/1246?
I'm pretty sure it fixes the former.

**Comment by evverx** [comment]
I'm not sure it works as expected. With this patch applied (with the same token) I got
```
{
  "date": "2021-11-11",
  "repo": {
    "name": "github.com/evverx/systemd",
    "commit": "33796123bccabdcc91ee9b87b5c042710bf50362"
  },
  "scorecard": {
    "version": "3.1.1-47-ga15225c",
    "commit": "a15225c59c0fb7d60f139795882990f8fde7badd"
  },
  "score": 3.0,
  "checks": [
    {
      "details": [
        "Warn: 'force pushes' enabled on branch 'main'",
        "Info: 'allow deletion' disabled on branch 'main'",
        "Warn: linear history disabled on branch 'main'",
        "Warn: 'administrator' PRs are exempt from reviews on branch 'main'",
        "Info: strict status check enabled on branch 'main'",
        "Warn: status checks for merging have no specific status to check on branch 'main'",
        "Warn: number of required reviewers is only 0 on branch 'main'",
        "Info: Stale review dismissal enabled on branch 'main'",
        "Warn: Owner review not required on branch 'main'"
      ],
      "score": 3,
      "reason": "branch protection is not maximal on development and all release branches",
      "name": "Branch-Protection",
      "documentation": {
        "url": "https://github.com/ossf/scorecard/blob/a15225c59c0fb7d60f139795882990f8fde7badd/docs/checks.md#branch-protection",
        "short": "Determines if the default and release branches are protected with GitHub's branch protection settings."
      }
    }
  ],
  "metadata": null
}
```
and here's what the rules look like
```
{
  "url": "https://api.github.com/repos/evverx/systemd/branches/main/protection",
  "required_pull_request_reviews": {
    "url": "https://api.github.com/repos/evverx/systemd/branches/main/protection/required_pull_request_reviews",
    "dismiss_stale_reviews": true,
    "require_code_owner_reviews": false,
    "required_approving_review_count": 2
  },
  "required_signatures": {
    "url": "https://api.github.com/repos/evverx/systemd/branches/main/protection/required_signatures",
    "enabled": false
  },
  "enforce_admins": {
    "url": "https://api.github.com/repos/evverx/systemd/branches/main/protection/enforce_admins",
    "enabled": false
  },
  "required_linear_history": {
    "enabled": false
  },
  "allow_force_pushes": {
    "enabled": true
  },
  "allow_deletions": {
    "enabled": false
  },
  "required_conversation_resolution": {
    "enabled": false
  }
}
```
It seems at least two subchecks aren't correct

**Comment by azeemshaikh38** [comment]
> It seems at least two subchecks aren't correct

This is very surprising. I tested this PR both against your repo and a personal repo with an admin token and it is returning the expected results (matching with GitHub API). My only hunch here would be that somehow there is a delay between GitHub REST API and GraphQL APIs, so when you modify the settings and immediately test with Scorecard, the results seem off.

I'm going to submit this PR for now, since it is clearly an improvement over what we have today. Could you please try once more after the PR is submitted and let me know the results? If the issue persists, we can continue the debugging over #1246  and #1247.

**Pull request merged**
