### PR TITLE
Add packaging check.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Review by naveensrinivasan — COMMENTED** [review]
As we are adding code, unit tests, and e2e will build confidence. I would recommend that we don't merge code without tests.

**Comment by inferno-chromium** [comment]
> As we are adding code, unit tests, and e2e will build confidence. I would recommend that we don't merge code without tests.

Added e2e test, i need to think more on how to write unittests for these workflows. If you have ideas, can you give it a try. I will think in a week or two, right now busy with other stuff. definitely do want tests for these.

**Comment by naveensrinivasan** [comment]
> > As we are adding code, unit tests, and e2e will build confidence. I would recommend that we don't merge code without tests.
> 
> Added e2e test, i need to think more on how to write unittests for these workflows. If you have ideas, can you give it a try or provide suggestions. I will think in a week or two, right now busy with other stuff. definitely do want tests for these.
> 
> @naveensrinivasan - can you review this.
@inferno-chromium  I can take a stab a writing unit-tests for this. And then we can merge this. Let me know your thoughts?

**Comment by inferno-chromium** [comment]
> > > As we are adding code, unit tests, and e2e will build confidence. I would recommend that we don't merge code without tests.
> > 
> > 
> > Added e2e test, i need to think more on how to write unittests for these workflows. If you have ideas, can you give it a try or provide suggestions. I will think in a week or two, right now busy with other stuff. definitely do want tests for these.
> > @naveensrinivasan - can you review this.
> > @inferno-chromium  I can take a stab a writing unit-tests for this. And then we can merge this. Let me know your thoughts?

Your change can be in a new PR, lets merge this. No need to merge in this. wdyt?

**Comment by naveensrinivasan** [comment]
@inferno-chromium   Sounds good. 

Can this be addressed before merging the PR?
image

**Comment by inferno-chromium** [comment]
> @inferno-chromium Sounds good.
> 
> Can this be addressed before merging the PR?
> image

Done!

**Comment by naveensrinivasan** [comment]
> > @inferno-chromium Sounds good.
> > Can this be addressed before merging the PR?
> > image
> 
> Done!

Thanks!

**Review by naveensrinivasan — APPROVED** [review]

**Pull request merged**
