### PR TITLE
:sparkles: Gitlab support

### PR DESCRIPTION
**Pull request by N8BWert**
#### What kind of change does this PR introduce?
This PR introduces GitLab functionality to the scorecard project.

#### What is the current behavior?
Currently scorecard only supports testing GitHub repositories.

#### What is the new behavior (if this is a feature change)?**
A client has been added to allow the command line execution of scorecard to include support for gitlab projects.

#### Which issue(s) this PR fixes
[#Support For GitLab Projects](https://github.com/ossf/scorecard/issues/2266#issue-1374875930)
https://github.com/ossf/scorecard/issues/2266#issue-1374875930

#### Special notes for your reviewer
It is important to note that projectID is not the same as the name of the project.  Scorecard will not find the GitLab project in the following situation:

Example: Project named test-project with projectID 1234 owned by steve who is a part of examplecompany
- This will not work:
```
scorecard gitlab.examplecompany.com/steve/test-project
```
+ However this will work:
```
scorecard gitlab.examplecompany.com/steve/1234
```

#### Does this PR introduce a user-facing change?
If a user is running scorecard on a GitHub repository that includes the string "gitlab." in the title scorecard will now think that repository is actually a GitLab project, however this is an incredibly rare edge case.

```release-note
Repositories that include "gitlab." in their title will be assumed to be gitlab projects.
```

### CODE REVIEW

**Comment by azeemshaikh38** [comment]
@N8BWert thank you so much for this PR! Very excited to see Scorecard support GitLab. I'm ooo today, will review it tomo.

**Review by laurentsimon — APPROVED** [review]
Looks amazing. Thanks for this PR. 
A few things we can iterate on after merging are:
1. Handling of tokens
2. Adding e2e tests under the `./e2e/ folder.
3. Scanning of critical repositories in the cron jobs (under `./cron` folder)

I'd suggest we add a "experimental feature" in the README until we have the e2e tests in.

**Review by naveensrinivasan — CHANGES_REQUESTED** [review]
Thank you! This is great! Without tests, it is going to be hard to maintain this. Could you please add tests?

**Comment by laurentsimon** [comment]
@naveensrinivasan which tests specifically? Under `clients/gitlabrepo`? Or end-to-end tests?
Since this is a massive PR and still experimental, I think it'd be OK to do the e2e tests in a follow-up PR. Wdut?

**Comment by N8BWert** [comment]
@naveensrinivasan By tests do you mean the e2e tests.  If so, would you like me to host all of the e2e test repos on my gitlab or is there a plan to make a fork of those repos into an ossf specific GitLab?

**Comment by laurentsimon** [comment]
I think we should take the second option: have an ossf GitLab org

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan which tests specifically? Under `clients/gitlabrepo`? Or end-to-end tests?
> Since this is a massive PR and still experimental, I think it'd be OK to do the e2e tests in a follow-up PR. Wdut?

Both TBH. I recommend we do the e2e and merge them in, as it provides some sanity. If not, we are blindsided whether any of these features are working. That is my thought process.

**Comment by naveensrinivasan** [comment]
> @naveensrinivasan By tests do you mean the e2e tests. If so, would you like me to host all of the e2e test repos on my gitlab or is there a plan to make a fork of those repos into an ossf specific GitLab?

If the e2e tests are in GitLab how do we ensure in this repository that new code changes aren't breaking this functionality? Do you have ideas?

**Comment by N8BWert** [comment]
Sounds good to me!

**Review by azeemshaikh38 — APPROVED** [review]
Thanks for this incredible PR @N8BWert! This looks good to submit overall. I left some comments, please address those and I can work on getting this merged in. My high-level comments on the PR is:

- Let's confine this PR to changes made within `clients/gitlabrepo/` package only. You can add the integrated support for GitLab in a future PR. 
- Remove any dead code that is still WIP and submit it in a future PR.
- Please add some unit tests for code where parsing/string building logic exists.
- There are some linter errors/warnings. Please fix those to adhere to our projects coding guidelines.

**Comment by N8BWert** [comment]
@azeemshaikh38 Sounds good, on it now.

**Comment by azeemshaikh38** [comment]
@laurentsimon @naveensrinivasan @N8BWert - regarding e2e: we might be biting off more than we can chew by attempting this all in a single PR. My suggestion would be to get this PR merged in with just code inside `clients/gitlabrepo`. We can look into adding support for e2e tests and fully supporting this in the CLI in separate smaller PRs. Wdyt?

Note that `gitlabrepo` implementation isn't fully completed yet (which is fine cause this PR adds >90% support for it already).

**Comment by laurentsimon** [comment]
I'm fine with adding e2etests later, see https://github.com/ossf/scorecard/pull/2265#issuecomment-1249504776

**Comment by azeemshaikh38** [comment]
> I'm fine with adding e2etests later, see [#2265 (comment)](https://github.com/ossf/scorecard/pull/2265#issuecomment-1249504776)

Ah I see. In that case, @naveensrinivasan do you still prefer having e2e tests? Note that this PR won't contain any logic outside `clients/gitlabrepo` segregating it from the core Scorecard logic and allowing us to test it piece by piece. Does that work?

**Comment by naveensrinivasan** [comment]
> > I'm fine with adding e2etests later, see [#2265 (comment)](https://github.com/ossf/scorecard/pull/2265#issuecomment-1249504776)
> 
> Ah I see. In that case, @naveensrinivasan do you still prefer having e2e tests? Note that this PR won't contain any logic outside `clients/gitlabrepo` segregating it from the core Scorecard logic and allowing us to test it piece by piece. Does that work?

That works for me! Thanks

**Review by naveensrinivasan — APPROVED** [review]
Thank you!

**Comment by azeemshaikh38** [comment]
@N8BWert could you update your branch and resolve pending conflicts here? I will get this PR merged in so that review of #2280 can be unblocked.

**Pull request merged**
