### PR TITLE
📖 👻 Minor grammar/readability docs fix

### PR DESCRIPTION
**Pull request by ben-moss**
* **Please check if the PR fulfills these requirements**
- [x] N/A ~Tests for the changes have been added (for bug fixes / features)~
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Very minor typos in docs

* **What is the current behavior?** (You can also link to an open issue here)

N/A

* **What is the new behavior (if this is a feature change)?**

N/A (no change in behaviour)

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

### CODE REVIEW

**Review by azeemshaikh38 — APPROVED** [review]
Thanks!

**Review by azeemshaikh38 — COMMENTED** [review]
I forgot that we auto-generate docs using `checks.yaml` and do not modify this file directly. Updated the `checks.yaml` in #659 to reflect this change.

**Comment by ben-moss** [comment]
> I forgot that we auto-generate docs using `checks.yaml` and do not modify this file directly. Updated the `checks.yaml` in #659 to reflect this change.

Ah, sorry. That's good to know. Would it be worth noting that in the contributing guide @azeemshaikh38 ?

**Comment by azeemshaikh38** [comment]
I think this is mentioned already in `checks.md` - https://raw.githubusercontent.com/ossf/scorecard/main/checks/checks.md. Maybe we should just make it more easily visible.

**Pull request merged**
