### PR TITLE
:book: Update bestpractices links

### PR DESCRIPTION
**Pull request by fredgan**
#### What kind of change does this PR introduce?

 Update BestPractices links where they currently redirect.

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

#### What is the current behavior?

Old domain name `bestpractices.coreinfrastructure.org` are used in the BestPractices.

#### What is the new behavior (if this is a feature change)?**

New domain name `www.bestpractices.dev` are used in the BestPractices.

- [ ] Tests for the changes have been added (for bug fixes/features)

#### Which issue(s) this PR fixes

NONE

#### Special notes for your reviewer

NONE

#### Does this PR introduce a user-facing change?

```release-note
Update new domain name of Best Practices.
```

### CODE REVIEW

**Review by spencerschrock — APPROVED** [review]
Thanks. 

For myself and others, here's some context: https://github.com/coreinfrastructure/best-practices-badge/pull/2043

**Comment by spencerschrock** [comment]
@fredgan can you please DCO the commit? These instructions come from the `Details` link of the DCO check/status.

> To add your Signed-off-by line to every commit in this branch:
>
> Ensure you have a local copy of your branch by [checking out the pull request locally via command line](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally).
> In your local branch, run: git rebase HEAD~1 --signoff
> Force push your changes to overwrite the branch: git push --force-with-lease origin fix_bestpractices_links

**Comment by gabibguti** [comment]
LGTM

DCO Bot is still complaining about a missing whitespace in the signoff name:
Expected "Fred Gan [ganshaolong@vip.qq.com](mailto:ganshaolong@vip.qq.com)", but got "FredGan [ganshaolong@vip.qq.com](mailto:ganshaolong@vip.qq.com)".
Did you use the `git rebase HEAD~1 --signoff` command?

**Comment by fredgan** [comment]
Fixed, thanks @spencerschrock @gabibguti

**Pull request merged**
