### PR TITLE
:warning: refactor: rename fields on Branch Protection Pull Request rules

### PR DESCRIPTION
**Pull request by diogoteles08**
This change was briefly discussed at https://github.com/ossf/scorecard/pull/3728#discussion_r1424035403

This PR solely renames part of the structure that represents Branch Protection rules.
Inside the structure clients.BranchRef.BranchProtectionRule, I'm renaming RequiredPullRequestReviews to PullRequestRule.

The previous struct declaration is the following:
```
type RequiredPullRequestReviews struct {
	Required                     *bool // are PRs required
	RequiredApprovingReviewCount *int32
	DismissStaleReviews          *bool
	RequireCodeOwnerReviews      *bool
}
```
The reason is that the field doesn't refer only to Required reviews of pull requests, it refers to different Branch protection rules around Pull Requests. More specifically, it has the field `Required`, that states if PRs are either required or not to make changes to that branch. The path `RequiredPullRequestReviews.Required` could get confusion, while `PullRequestRule.Required` is clearer. Additionally, all the other fields inside that struct already have the word "Review" on it, so it's redundant to have it also on the struct name.

#### What kind of change does this PR introduce?

Refactor

- [x] PR title follows the guidelines defined in our [pull request documentation](https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process)

**This PR would probably be a breaking change because the changed struct is shared externally**

### CODE REVIEW

**Comment by spencerschrock** [comment]
This would probably be a breaking (`:warning:`) change, given it's changing a struct in one of our main interfaces. With V5 on the horizon, it's something we can do. But would be good to properly categorize

**Comment by diogoteles08** [comment]
@spencerschrock Sorry, I forgot about this detail. I updated the PR title and the end of its description, PTAL

**Comment by spencerschrock** [comment]
> @spencerschrock Sorry, I forgot about this detail. I updated the PR title and the end of its description, PTAL

Now that #3759 is merged, this would need rebased (recreating + force pushing might just be easier). Overall, renaming SGTM.

**Comment by diogoteles08** [comment]
@spencerschrock rebased as requested =)

**Review by spencerschrock — APPROVED** [review]

**Pull request merged**
