### PR TITLE
✨ Provide remediation suggestions in results

### LINKED ISSUE #304: Feature - Provide Remediation in results
**Is your feature request related to a problem? Please describe.**
Provide description and remediation in the results. Related to #63 
This is also required for https://github.com/ossf/scorecard/issues/193

- [ ] Active
- [ ] Branch-Protection
- [ ] CI-Tests,CII-Best-Practices
- [ ] Code-Review,Contributors
- [ ] Frozen-Deps,Fuzzing
- [ ] Packaging 
- [ ] Pull-Requests
- [ ] SAST
- [ ] Security-Policy
- [ ] Signed-Releases
- [ ] Signed-Tags

### PR DESCRIPTION
**Pull request by chrismcgehee**
* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] PR title follows the guidelines defined in  https://github.com/ossf/scorecard/blob/main/CONTRIBUTING.md#pr-process

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
Remediation results are not included in the terminal results
Closes #304 

* **What is the new behavior (if this is a feature change)?**
When run with the `--show-details` flag, the results in the terminal will include remediation suggestions. Remediation will only be displayed if the check has a certain level of confidence (currently 5 or higher but I'm open to modifying that number). This should prevent remediation steps from showing if the check failed due to internal issues such as being rate-limited in API requests.

The remediation steps are pulled from `checks.yaml` which will be embedded into the `scorecard` binary. This PR increases the size of the binary from 19.93MB. to 19.95MB.

If a check has differing remediation steps based on the specific issue found, then codes can be assigned to those issues and those codes can be associated to specific remediation steps in `checks.yaml`. See "Frozen-Deps" as an example. If a set of remediation steps is not associated here with any code, those steps will be included for any failed check.

Here is a partial view of output that includes remediation steps:
image
Notice that the remediation results include markdown syntax. I thought about ways to scrub the markdown but I couldn't think of a way to do it that didn't disrupt the flow of the sentence.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
Here are some areas I'd like feedback on:
- Is 5 the right confidence level for displaying remediation?
- Should there be a separate flag for displaying remediation? Or should it always be displayed?
- Is there a decent way to clean up the markdown syntax in the results?

### CODE REVIEW

**Review by azeemshaikh38 — COMMENTED** [review]
IIUC, this PR is similar to Laurent's PR - #650, so adding @laurentsimon as a reviewer. 

Let's discuss both these PRs in next week's meet. Most of us might be out this week.

**Comment by chrismcgehee** [comment]
> IIUC, this PR is similar to Laurent's PR - #650, so adding @laurentsimon as a reviewer.

Yeah, it looks like this is similar. 
> Let's discuss both these PRs in next week's meet. Most of us might be out this week.

I won't be able to attend this meeting since that's moving day. I'll do my best to make the next one.

**Comment by naveensrinivasan** [comment]
@laurentsimon  / @chrismcgehee  What do we want to do with this PR?

**Comment by chrismcgehee** [comment]
> @laurentsimon / @chrismcgehee What do we want to do with this PR?

I see that now `--show-details` has a DOCUMENTATION/REMEDIATION column. I think that's probably sufficient, so I wouldn't mind closing this PR.

**Comment by inferno-chromium** [comment]
> > @laurentsimon / @chrismcgehee What do we want to do with this PR?
> 
> I see that now `--show-details` has a DOCUMENTATION/REMEDIATION column. I think that's probably sufficient, so I wouldn't mind closing this PR.

yes right, laurent landed this a week or two back, closing. there are lot of new things to do, can discuss in next biweekly. sorry for duplication.

**Pull request closed without merging**
