### PR TITLE
✨ npm only allows `npm ci`

### PR DESCRIPTION
**Pull request by laurentsimon**
`npm ci` is the only command that honors hashes and verifies them. Other commands like `npm install`, `npm update` should never base used in scripts. Updates should be performed via a tool like dependabot/renovabot. 
even in the presence of a lock files, `npm install` may pull in un-pinned dependencies if some dependencies are not present in the lock file.

close https://github.com/ossf/scorecard/issues/1175

### CODE REVIEW

**Comment by laurentsimon** [comment]
@rsprabery comments?

**Comment by laurentsimon** [comment]
FYI @naveensrinivasan @azeemsgoogle I don't seem to require an approve for integration test. I think that's because I'm in the team.

**Comment by laurentsimon** [comment]
@naveensrinivasan @azeemsgoogle please help me with integration tests. Thanks

**Comment by azeemshaikh38** [comment]
> FYI @naveensrinivasan @azeemsgoogle can one of you approve to run the integration tests? Thanks

Done

**Review by oliverchang — APPROVED** [review]

**Comment by laurentsimon** [comment]
@naveensrinivasan @azeemsgoogle any idea what's the reason for a blank Validation test result https://github.com/ossf/scorecard/runs/4292383384?check_suite_focus=true? First time I've seen this.

**Pull request merged**
